; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_7CombFilter@@6B@				; CombFilter::`vftable'
PUBLIC	??_R3CombFilter@@8				; CombFilter::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R1A@?0A@EA@CombFilter@@8			; CombFilter::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R2CombFilter@@8				; CombFilter::`RTTI Base Class Array'
PUBLIC	??_R4CombFilter@@6B@				; CombFilter::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCombFilter@@@8				; CombFilter `RTTI Type Descriptor'
;	COMDAT ??_R0?AVCombFilter@@@8
data$rs	SEGMENT
??_R0?AVCombFilter@@@8 DQ FLAT:??_7type_info@@6B@	; CombFilter `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVCombFilter@@', 00H
data$rs	ENDS
;	COMDAT ??_R4CombFilter@@6B@
rdata$r	SEGMENT
??_R4CombFilter@@6B@ DD 01H				; CombFilter::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVCombFilter@@@8
	DD	imagerel ??_R3CombFilter@@8
	DD	imagerel ??_R4CombFilter@@6B@
rdata$r	ENDS
;	COMDAT ??_R2CombFilter@@8
rdata$r	SEGMENT
??_R2CombFilter@@8 DD imagerel ??_R1A@?0A@EA@CombFilter@@8 ; CombFilter::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@Delay@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CombFilter@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CombFilter@@8 DD imagerel ??_R0?AVCombFilter@@@8 ; CombFilter::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3CombFilter@@8
rdata$r	ENDS
;	COMDAT ??_R3CombFilter@@8
rdata$r	SEGMENT
??_R3CombFilter@@8 DD 00H				; CombFilter::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2CombFilter@@8
rdata$r	ENDS
;	COMDAT ??_7CombFilter@@6B@
CONST	SEGMENT
??_7CombFilter@@6B@ DQ FLAT:??_R4CombFilter@@6B@	; CombFilter::`vftable'
	DQ	FLAT:?init@Delay@@UEAAXMH@Z
	DQ	FLAT:?setSampleRate@Delay@@UEAAXH@Z
	DQ	FLAT:?processAudio@CombFilter@@UEAAMM@Z
PUBLIC	?setFeedbackToNegative@CombFilter@@QEAAXXZ	; CombFilter::setFeedbackToNegative
PUBLIC	?processAudio@CombFilter@@UEAAMM@Z		; CombFilter::processAudio
PUBLIC	?setFeedbackFromDecay@CombFilter@@QEAAXM@Z	; CombFilter::setFeedbackFromDecay
PUBLIC	?setFeedback@CombFilter@@QEAAXM@Z		; CombFilter::setFeedback
PUBLIC	??1CombFilter@@QEAA@XZ				; CombFilter::~CombFilter
PUBLIC	??0CombFilter@@QEAA@XZ				; CombFilter::CombFilter
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processAudio@CombFilter@@UEAAMM@Z DD imagerel $LN10
	DD	imagerel $LN10+89
	DD	imagerel $unwind$?processAudio@CombFilter@@UEAAMM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?setFeedbackFromDecay@CombFilter@@QEAAXM@Z DD imagerel $LN4
	DD	imagerel $LN4+78
	DD	imagerel $unwind$?setFeedbackFromDecay@CombFilter@@QEAAXM@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?setFeedbackFromDecay@CombFilter@@QEAAXM@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processAudio@CombFilter@@UEAAMM@Z DD 010401H
	DD	04204H
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
;	COMDAT ??0CombFilter@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0CombFilter@@QEAA@XZ PROC				; CombFilter::CombFilter, COMDAT
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 8    : 	dly_buffer				= NULL;

	xor	edx, edx

; 10   : 	dly_makeUpGain			= 1.0;

	mov	QWORD PTR [rcx+52], 1065353216		; 3f800000H
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp

; 8    : {

	lea	rax, OFFSET FLAT:??_7CombFilter@@6B@
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 8    : 	dly_buffer				= NULL;

	mov	QWORD PTR [rcx+40], rdx
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp

; 8    : {

	mov	QWORD PTR [rcx], rax

; 12   : }

	mov	rax, rcx
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 9    : 	dly_makeUpGaindB		= 0.0;

	mov	DWORD PTR [rcx+48], edx

; 11   : 	dly_delayInmsec			= 0.0;
; 12   : 	dly_delayInSamples		= 0.0;

	mov	QWORD PTR [rcx+20], rdx

; 13   : 	dly_readIndex			= 0;

	mov	QWORD PTR [rcx+28], rdx

; 14   : 	dly_writeIndex			= 0;
; 15   : 	dly_lineLengthInSamples = 0;

	mov	QWORD PTR [rcx+12], rdx
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp

; 10   : 	cf_decayInSeconds   = 0.0;

	mov	DWORD PTR [rcx+60], edx

; 11   : 	cf_feedbackGainSign = 1;

	mov	DWORD PTR [rcx+64], 1

; 12   : }

	ret	0
??0CombFilter@@QEAA@XZ ENDP				; CombFilter::CombFilter
_TEXT	ENDS
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
;	COMDAT ??1CombFilter@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1CombFilter@@QEAA@XZ PROC				; CombFilter::~CombFilter, COMDAT

; 15   : CombFilter::~CombFilter() {}

	lea	rax, OFFSET FLAT:??_7CombFilter@@6B@
	mov	QWORD PTR [rcx], rax
	jmp	??1Delay@@QEAA@XZ			; Delay::~Delay
??1CombFilter@@QEAA@XZ ENDP				; CombFilter::~CombFilter
_TEXT	ENDS
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
;	COMDAT ?setFeedback@CombFilter@@QEAAXM@Z
_TEXT	SEGMENT
this$ = 8
g$dead$ = 16
?setFeedback@CombFilter@@QEAAXM@Z PROC			; CombFilter::setFeedback, COMDAT

; 19   : 	cf_feedbackGain = g;

	and	DWORD PTR [rcx+56], 0

; 20   : }

	ret	0
?setFeedback@CombFilter@@QEAAXM@Z ENDP			; CombFilter::setFeedback
_TEXT	ENDS
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
;	COMDAT ?setFeedbackFromDecay@CombFilter@@QEAAXM@Z
_TEXT	SEGMENT
this$ = 48
decayInSeconds$ = 56
?setFeedbackFromDecay@CombFilter@@QEAAXM@Z PROC		; CombFilter::setFeedbackFromDecay, COMDAT

; 23   : {

$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H

; 24   : 	// set decay
; 25   : 	cf_decayInSeconds = decayInSeconds;
; 26   : 	
; 27   : 	// compute comb filter gain module according to given decay value (in seconds)
; 28   : 	float feedbackModule = pow(10, -3 * dly_delayInmsec / (cf_decayInSeconds * 1000));

	movss	xmm0, DWORD PTR __real@bb449ba6
	mov	rbx, rcx
	divss	xmm0, xmm1
	movss	DWORD PTR [rcx+60], xmm1
	mulss	xmm0, DWORD PTR [rcx+24]
	cvtps2pd xmm1, xmm0
	movsd	xmm0, QWORD PTR __real@4024000000000000
	call	QWORD PTR __imp_pow
	movd	xmm2, DWORD PTR [rbx+64]
	xorps	xmm1, xmm1
	cvtsd2ss xmm1, xmm0

; 29   : 
; 30   : 	// allocate comb filter gain value retaining its sign
; 31   : 	cf_feedbackGain = cf_feedbackGainSign * feedbackModule;

	cvtdq2ps xmm2, xmm2
	mulss	xmm2, xmm1
	movss	DWORD PTR [rbx+56], xmm2

; 32   : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?setFeedbackFromDecay@CombFilter@@QEAAXM@Z ENDP		; CombFilter::setFeedbackFromDecay
_TEXT	ENDS
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
;	COMDAT ?processAudio@CombFilter@@UEAAMM@Z
_TEXT	SEGMENT
this$ = 48
xn$ = 56
?processAudio@CombFilter@@UEAAMM@Z PROC			; CombFilter::processAudio, COMDAT

; 35   : {

$LN10:
	sub	rsp, 40					; 00000028H
	movaps	xmm4, xmm1
	mov	r9, rcx

; 36   : 	// Extract value from delay buffer
; 37   : 	float yn = readFromDelayLine();

	call	?readFromDelayLine@Delay@@QEAAMXZ	; Delay::readFromDelayLine
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 176  : 	dly_buffer[dly_writeIndex] = xn;

	movsxd	rdx, DWORD PTR [r9+32]
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp

; 40   : 	float buff = xn + cf_feedbackGain * yn;

	movaps	xmm3, xmm0
	mulss	xmm3, DWORD PTR [r9+56]
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 176  : 	dly_buffer[dly_writeIndex] = xn;

	mov	rax, QWORD PTR [r9+40]
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp

; 40   : 	float buff = xn + cf_feedbackGain * yn;

	addss	xmm3, xmm4
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 176  : 	dly_buffer[dly_writeIndex] = xn;

	movss	DWORD PTR [rax+rdx*4], xmm3

; 162  : 	if (dly_readIndex >= dly_lineLengthInSamples)

	xor	edx, edx
	inc	DWORD PTR [r9+28]
	mov	ecx, DWORD PTR [r9+12]
	cmp	DWORD PTR [r9+28], ecx
	jl	SHORT $LN6@processAud

; 163  : 		dly_readIndex = 0;

	mov	DWORD PTR [r9+28], edx
$LN6@processAud:

; 164  : 
; 165  : 	// Increase writing index
; 166  : 	dly_writeIndex++;

	inc	DWORD PTR [r9+32]

; 169  : 	if (dly_writeIndex >= dly_lineLengthInSamples)

	mov	eax, DWORD PTR [r9+32]
	cmp	eax, ecx
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp

; 49   : 	return yn * dly_makeUpGain;

	mulss	xmm0, DWORD PTR [r9+52]
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 169  : 	if (dly_writeIndex >= dly_lineLengthInSamples)

	cmovge	eax, edx
	mov	DWORD PTR [r9+32], eax
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp

; 50   : }

	add	rsp, 40					; 00000028H
	ret	0
?processAudio@CombFilter@@UEAAMM@Z ENDP			; CombFilter::processAudio
_TEXT	ENDS
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
;	COMDAT ?setFeedbackToNegative@CombFilter@@QEAAXXZ
_TEXT	SEGMENT
this$ = 8
?setFeedbackToNegative@CombFilter@@QEAAXXZ PROC		; CombFilter::setFeedbackToNegative, COMDAT

; 54   : 	cf_feedbackGainSign = -1;

	or	DWORD PTR [rcx+64], -1

; 55   : }

	ret	0
?setFeedbackToNegative@CombFilter@@QEAAXXZ ENDP		; CombFilter::setFeedbackToNegative
_TEXT	ENDS
END
