; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp_fftw_free:PROC
EXTRN	__imp_fftw_execute:PROC
EXTRN	__imp_fftw_destroy_plan:PROC
EXTRN	__imp_fftw_plan_dft_1d:PROC
EXTRN	__imp_cos:PROC
EXTRN	__imp_fftw_malloc:PROC
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	?doOverlapAdd@PhaseVocoder@@QEAAXPEANH@Z	; PhaseVocoder::doOverlapAdd
PUBLIC	?doInverseFFT@PhaseVocoder@@QEAAXXZ		; PhaseVocoder::doInverseFFT
PUBLIC	?processAudioSample@PhaseVocoder@@QEAANNAEA_N@Z	; PhaseVocoder::processAudioSample
PUBLIC	?advanceAndCheckFFT@PhaseVocoder@@QEAA_NXZ	; PhaseVocoder::advanceAndCheckFFT
PUBLIC	?initialize@PhaseVocoder@@QEAAXIIW4windowType@@@Z ; PhaseVocoder::initialize
PUBLIC	?destroyFFTW@PhaseVocoder@@QEAAXXZ		; PhaseVocoder::destroyFFTW
PUBLIC	??_H@YAXPEAX_K1P6APEAX0@Z@Z			; `vector constructor iterator'
?kCTCorrFactorAntiLog@@3NB DQ 01H DUP (?)		; kCTCorrFactorAntiLog
?kCTCorrFactorZero@@3NB DQ 01H DUP (?)			; kCTCorrFactorZero
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?doInverseFFT@PhaseVocoder@@QEAAXXZ DD imagerel $LN4@doInverseF
	DD	imagerel $LN4@doInverseF+29
	DD	imagerel $unwind$?doInverseFFT@PhaseVocoder@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processAudioSample@PhaseVocoder@@QEAANNAEA_N@Z DD imagerel $LN8@processAud
	DD	imagerel $LN8@processAud+160
	DD	imagerel $unwind$?processAudioSample@PhaseVocoder@@QEAANNAEA_N@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?advanceAndCheckFFT@PhaseVocoder@@QEAA_NXZ DD imagerel $LN18@advanceAnd
	DD	imagerel $LN18@advanceAnd+176
	DD	imagerel $unwind$?advanceAndCheckFFT@PhaseVocoder@@QEAA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?initialize@PhaseVocoder@@QEAAXIIW4windowType@@@Z DD imagerel $LN64@initialize
	DD	imagerel $LN64@initialize+1191
	DD	imagerel $unwind$?initialize@PhaseVocoder@@QEAAXIIW4windowType@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?destroyFFTW@PhaseVocoder@@QEAAXXZ DD imagerel $LN9@destroyFFT
	DD	imagerel $LN9@destroyFFT+89
	DD	imagerel $unwind$?destroyFFTW@PhaseVocoder@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_H@YAXPEAX_K1P6APEAX0@Z@Z DD imagerel $LN13@vector
	DD	imagerel $LN13@vector+47
	DD	imagerel $unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__EkCTCorrFactorAntiLog@@YAXXZ DD imagerel ??__EkCTCorrFactorAntiLog@@YAXXZ
	DD	imagerel ??__EkCTCorrFactorAntiLog@@YAXXZ+47
	DD	imagerel $unwind$??__EkCTCorrFactorAntiLog@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__EkCTCorrFactorZero@@YAXXZ DD imagerel ??__EkCTCorrFactorZero@@YAXXZ
	DD	imagerel ??__EkCTCorrFactorZero@@YAXXZ+39
	DD	imagerel $unwind$??__EkCTCorrFactorZero@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
?kCTCorrFactorZero$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorZero@@YAXXZ ; kCTCorrFactorZero$initializer$
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__EkCTCorrFactorZero@@YAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__EkCTCorrFactorAntiLog@@YAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?destroyFFTW@PhaseVocoder@@QEAAXXZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?initialize@PhaseVocoder@@QEAAXIIW4windowType@@@Z DQ 000037843000e4301r ; 4.82531e-309
	DQ	0001064180004681fr		; 2.27945e-308
	DQ	0000e3418000f5418r		; 1.97524e-308
	DQ	07010d012f0149218r		; 6.52554e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?advanceAndCheckFFT@PhaseVocoder@@QEAA_NXZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processAudioSample@PhaseVocoder@@QEAANNAEA_N@Z DQ 00002781e00081e01r ; 3.43386e-309
	DQ	0000a340a00036816r		; 1.41894e-308
	DD	07006720aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?doInverseFFT@PhaseVocoder@@QEAAXXZ DQ 03002320600020601r ; 1.96423e-77
CRT$XCU	SEGMENT
?kCTCorrFactorUnity$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorUnity@@YAXXZ ; kCTCorrFactorUnity$initializer$
CRT$XCU	ENDS
CRT$XCU	SEGMENT
?kCTCorrFactorAntiUnity$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorAntiUnity@@YAXXZ ; kCTCorrFactorAntiUnity$initializer$
CRT$XCU	ENDS
CRT$XCU	SEGMENT
?kCTCorrFactorAntiLog$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorAntiLog@@YAXXZ ; kCTCorrFactorAntiLog$initializer$
CRT$XCU	ENDS
CRT$XCU	SEGMENT
?kCTCorrFactorAntiLogScale$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorAntiLogScale@@YAXXZ ; kCTCorrFactorAntiLogScale$initializer$
CRT$XCU	ENDS
CRT$XCU	ENDS
CRT$XCU	ENDS
CRT$XCU	ENDS
CRT$XCU	ENDS
CRT$XCU	ENDS
END
