; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_07GLGBIDLM@2nd?5Maj@			; `string'
PUBLIC	??_C@_07GNMKOBCE@3rd?5Min@			; `string'
PUBLIC	??_C@_07HLFHFJI@3rd?5Maj@			; `string'
PUBLIC	??_C@_07DOADDGAH@4th?5Per@			; `string'
PUBLIC	??_C@_07PCKJDGJJ@5th?5Per@			; `string'
PUBLIC	??_C@_07FLEHIOLN@6th?5Maj@			; `string'
PUBLIC	??_C@_07JHONIOCD@7th?5Maj@			; `string'
PUBLIC	??_C@_07JNPNFIPA@1st?5Oct@			; `string'
PUBLIC	??_C@_07EOOPKDLB@1?5Oct?$CL5@			; `string'
PUBLIC	??_C@_07FEMGBGFB@1?$CL2?5Oct@			; `string'
PUBLIC	??_C@_01LKDEMHDF@s@				; `string'
PUBLIC	??_C@_02EEKDFEKL@ms@				; `string'
PUBLIC	??_C@_08JGILNPHN@Disabled@			; `string'
PUBLIC	??_C@_07DOAOMMKG@Enabled@			; `string'
PUBLIC	??_C@_03INCOKCMB@Wet@				; `string'
PUBLIC	??_C@_07CNCNAGDO@Shimmer@			; `string'
PUBLIC	??_C@_05BFFNNFFO@Decay@				; `string'
PUBLIC	??_C@_04HIAEEHII@Damp@				; `string'
PUBLIC	??_C@_06LMOCGFEA@Spread@			; `string'
PUBLIC	??_C@_09ONNCCMEP@Intervals@			; `string'
PUBLIC	??_C@_0L@FMLEOGHL@Delay?5Damp@			; `string'
PUBLIC	??_C@_08GPJFBMJO@Delay?5FB@			; `string'
PUBLIC	??_C@_0L@OEGDAACC@Delay?5Leng@			; `string'
PUBLIC	??_C@_0L@HJEDBBAG@Enab?5BRDel@			; `string'
PUBLIC	??_C@_0L@LMBMODJO@Enab?5BRRev@			; `string'
PUBLIC	??_C@_0M@NKCEPMPP@Enab?5PShift@			; `string'
PUBLIC	??_C@_0L@HACKHIPL@Enab?5MSRev@			; `string'
PUBLIC	??_C@_07MCAEODGB@Default@			; `string'
PUBLIC	??_C@_06PIIHCPLG@Dreamy@			; `string'
PUBLIC	??_C@_05BCAGPPBA@Short@				; `string'
PUBLIC	??_C@_08FBELJDCF@Metallic@			; `string'
PUBLIC	??_C@_06LAKOKBGJ@Wobbly@			; `string'
PUBLIC	??_C@_09KHHOPKD@Fox?5Suite@			; `string'
PUBLIC	??_R0?AVPSMVocoder@@@8				; PSMVocoder `RTTI Type Descriptor'
PUBLIC	??_7Shimmer@@6B@				; Shimmer::`vftable'
PUBLIC	??_R3PSMVocoder@@8				; PSMVocoder::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R4IAudioSignalProcessor@@6B@			; IAudioSignalProcessor::`RTTI Complete Object Locator'
PUBLIC	??_R3IAudioSignalProcessor@@8			; IAudioSignalProcessor::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R1A@?0A@EA@Shimmer@@8			; Shimmer::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_7IAudioSignalProcessor@@6B@			; IAudioSignalProcessor::`vftable'
PUBLIC	??_R3Shimmer@@8					; Shimmer::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R1A@?0A@EA@IAudioSignalProcessor@@8		; IAudioSignalProcessor::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4PSMVocoder@@6B@				; PSMVocoder::`RTTI Complete Object Locator'
PUBLIC	??_R1A@?0A@EA@PSMVocoder@@8			; PSMVocoder::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4Shimmer@@6B@				; Shimmer::`RTTI Complete Object Locator'
PUBLIC	??_R2Shimmer@@8					; Shimmer::`RTTI Base Class Array'
PUBLIC	??_R0?AVShimmer@@@8				; Shimmer `RTTI Type Descriptor'
PUBLIC	??_R0?AVIAudioSignalProcessor@@@8		; IAudioSignalProcessor `RTTI Type Descriptor'
PUBLIC	??_R2PSMVocoder@@8				; PSMVocoder::`RTTI Base Class Array'
PUBLIC	??_7PSMVocoder@@6B@				; PSMVocoder::`vftable'
PUBLIC	??_R2IAudioSignalProcessor@@8			; IAudioSignalProcessor::`RTTI Base Class Array'
PUBLIC	?INTERVALS_NAMES_STRING@@3PAPEADA		; INTERVALS_NAMES_STRING
EXTRN	__imp_round:PROC
EXTRN	__imp_atan2:PROC
EXTRN	__imp_strcpy:PROC
EXTRN	__imp_abs:PROC
;	COMDAT ??_R2IAudioSignalProcessor@@8
rdata$r	SEGMENT
??_R2IAudioSignalProcessor@@8 DD imagerel ??_R1A@?0A@EA@IAudioSignalProcessor@@8 ; IAudioSignalProcessor::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_7PSMVocoder@@6B@
CONST	SEGMENT
??_7PSMVocoder@@6B@ DQ FLAT:??_R4PSMVocoder@@6B@	; PSMVocoder::`vftable'
	DQ	FLAT:?reset@PSMVocoder@@UEAA_NN@Z
	DQ	FLAT:?processAudioSample@PSMVocoder@@UEAANN@Z
	DQ	FLAT:?canProcessAudioFrame@PSMVocoder@@UEAA_NXZ
	DQ	FLAT:?setSampleRate@IAudioSignalProcessor@@UEAAXN@Z
	DQ	FLAT:?enableAuxInput@IAudioSignalProcessor@@UEAAX_N@Z
	DQ	FLAT:?processAuxInputAudioSample@IAudioSignalProcessor@@UEAANN@Z
	DQ	FLAT:?processAudioFrame@IAudioSignalProcessor@@UEAA_NPEBMPEAMII@Z
CONST	ENDS
;	COMDAT ??_R2PSMVocoder@@8
rdata$r	SEGMENT
??_R2PSMVocoder@@8 DD imagerel ??_R1A@?0A@EA@PSMVocoder@@8 ; PSMVocoder::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@IAudioSignalProcessor@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R0?AVIAudioSignalProcessor@@@8
data$rs	SEGMENT
??_R0?AVIAudioSignalProcessor@@@8 DQ FLAT:??_7type_info@@6B@ ; IAudioSignalProcessor `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVIAudioSignalProcessor@@', 00H
data$rs	ENDS
;	COMDAT ??_R0?AVShimmer@@@8
data$rs	SEGMENT
??_R0?AVShimmer@@@8 DQ FLAT:??_7type_info@@6B@		; Shimmer `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVShimmer@@', 00H
data$rs	ENDS
;	COMDAT ??_R2Shimmer@@8
rdata$r	SEGMENT
??_R2Shimmer@@8 DD imagerel ??_R1A@?0A@EA@Shimmer@@8	; Shimmer::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@AudioEffectX@@8
	DD	imagerel ??_R1A@?0A@EA@AudioEffect@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R4Shimmer@@6B@
rdata$r	SEGMENT
??_R4Shimmer@@6B@ DD 01H				; Shimmer::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVShimmer@@@8
	DD	imagerel ??_R3Shimmer@@8
	DD	imagerel ??_R4Shimmer@@6B@
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@PSMVocoder@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@PSMVocoder@@8 DD imagerel ??_R0?AVPSMVocoder@@@8 ; PSMVocoder::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3PSMVocoder@@8
rdata$r	ENDS
;	COMDAT ??_R4PSMVocoder@@6B@
rdata$r	SEGMENT
??_R4PSMVocoder@@6B@ DD 01H				; PSMVocoder::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVPSMVocoder@@@8
	DD	imagerel ??_R3PSMVocoder@@8
	DD	imagerel ??_R4PSMVocoder@@6B@
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@IAudioSignalProcessor@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IAudioSignalProcessor@@8 DD imagerel ??_R0?AVIAudioSignalProcessor@@@8 ; IAudioSignalProcessor::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3IAudioSignalProcessor@@8
rdata$r	ENDS
;	COMDAT ??_R3Shimmer@@8
rdata$r	SEGMENT
??_R3Shimmer@@8 DD 00H					; Shimmer::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	imagerel ??_R2Shimmer@@8
rdata$r	ENDS
;	COMDAT ??_7IAudioSignalProcessor@@6B@
CONST	SEGMENT
??_7IAudioSignalProcessor@@6B@ DQ FLAT:??_R4IAudioSignalProcessor@@6B@ ; IAudioSignalProcessor::`vftable'
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:?setSampleRate@IAudioSignalProcessor@@UEAAXN@Z
	DQ	FLAT:?enableAuxInput@IAudioSignalProcessor@@UEAAX_N@Z
	DQ	FLAT:?processAuxInputAudioSample@IAudioSignalProcessor@@UEAANN@Z
	DQ	FLAT:?processAudioFrame@IAudioSignalProcessor@@UEAA_NPEBMPEAMII@Z
CONST	ENDS
;	COMDAT ??_R1A@?0A@EA@Shimmer@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@Shimmer@@8 DD imagerel ??_R0?AVShimmer@@@8 ; Shimmer::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3Shimmer@@8
rdata$r	ENDS
;	COMDAT ??_R3IAudioSignalProcessor@@8
rdata$r	SEGMENT
??_R3IAudioSignalProcessor@@8 DD 00H			; IAudioSignalProcessor::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2IAudioSignalProcessor@@8
rdata$r	ENDS
;	COMDAT ??_R4IAudioSignalProcessor@@6B@
rdata$r	SEGMENT
??_R4IAudioSignalProcessor@@6B@ DD 01H			; IAudioSignalProcessor::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVIAudioSignalProcessor@@@8
	DD	imagerel ??_R3IAudioSignalProcessor@@8
	DD	imagerel ??_R4IAudioSignalProcessor@@6B@
rdata$r	ENDS
;	COMDAT ??_R3PSMVocoder@@8
rdata$r	SEGMENT
??_R3PSMVocoder@@8 DD 00H				; PSMVocoder::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2PSMVocoder@@8
rdata$r	ENDS
;	COMDAT ??_7Shimmer@@6B@
CONST	SEGMENT
??_7Shimmer@@6B@ DQ FLAT:??_R4Shimmer@@6B@		; Shimmer::`vftable'
	DQ	FLAT:??_EShimmer@@UEAAPEAXI@Z
	DQ	FLAT:?dispatcher@AudioEffectX@@UEAA_JHH_JPEAXM@Z
	DQ	FLAT:?open@AudioEffect@@UEAAXXZ
	DQ	FLAT:?close@AudioEffect@@UEAAXXZ
	DQ	FLAT:?suspend@AudioEffect@@UEAAXXZ
	DQ	FLAT:?resume@AudioEffectX@@UEAAXXZ
	DQ	FLAT:?setSampleRate@Shimmer@@UEAAXM@Z
	DQ	FLAT:?setBlockSize@AudioEffect@@UEAAXH@Z
	DQ	FLAT:?processReplacing@Shimmer@@UEAAXPEAPEAM0H@Z
	DQ	FLAT:?processDoubleReplacing@AudioEffect@@UEAAXPEAPEAN0H@Z
	DQ	FLAT:?setParameter@Shimmer@@UEAAXHM@Z
	DQ	FLAT:?getParameter@Shimmer@@UEAAMH@Z
	DQ	FLAT:?setParameterAutomated@AudioEffect@@UEAAXHM@Z
	DQ	FLAT:?getProgram@AudioEffect@@UEAAHXZ
	DQ	FLAT:?setProgram@Shimmer@@UEAAXH@Z
	DQ	FLAT:?setProgramName@AudioEffect@@UEAAXPEAD@Z
	DQ	FLAT:?getProgramName@Shimmer@@UEAAXPEAD@Z
	DQ	FLAT:?getParameterLabel@Shimmer@@UEAAXHPEAD@Z
	DQ	FLAT:?getParameterDisplay@Shimmer@@UEAAXHPEAD@Z
	DQ	FLAT:?getParameterName@Shimmer@@UEAAXHPEAD@Z
	DQ	FLAT:?getChunk@AudioEffect@@UEAAHPEAPEAX_N@Z
	DQ	FLAT:?setChunk@AudioEffect@@UEAAHPEAXH_N@Z
	DQ	FLAT:?setUniqueID@AudioEffect@@UEAAXH@Z
	DQ	FLAT:?setNumInputs@AudioEffect@@UEAAXH@Z
	DQ	FLAT:?setNumOutputs@AudioEffect@@UEAAXH@Z
	DQ	FLAT:?canProcessReplacing@AudioEffect@@UEAAX_N@Z
	DQ	FLAT:?canDoubleReplacing@AudioEffect@@UEAAX_N@Z
	DQ	FLAT:?programsAreChunks@AudioEffect@@UEAAX_N@Z
	DQ	FLAT:?setInitialDelay@AudioEffect@@UEAAXH@Z
	DQ	FLAT:?getEditor@AudioEffect@@UEAAPEAVAEffEditor@@XZ
	DQ	FLAT:?getAeffect@AudioEffect@@UEAAPEAUAEffect@@XZ
	DQ	FLAT:?getSampleRate@AudioEffect@@UEAAMXZ
	DQ	FLAT:?getBlockSize@AudioEffect@@UEAAHXZ
	DQ	FLAT:?getMasterVersion@AudioEffect@@UEAAHXZ
	DQ	FLAT:?getCurrentUniqueId@AudioEffect@@UEAAHXZ
	DQ	FLAT:?masterIdle@AudioEffect@@UEAAXXZ
	DQ	FLAT:?dB2string@AudioEffect@@UEAAXMPEADH@Z
	DQ	FLAT:?Hz2string@AudioEffect@@UEAAXMPEADH@Z
	DQ	FLAT:?ms2string@AudioEffect@@UEAAXMPEADH@Z
	DQ	FLAT:?float2string@AudioEffect@@UEAAXMPEADH@Z
	DQ	FLAT:?int2string@AudioEffect@@UEAAXHPEADH@Z
	DQ	FLAT:?__processDeprecated@AudioEffect@@UEAAXPEAPEAM0H@Z
	DQ	FLAT:?__getVuDeprecated@AudioEffect@@UEAAMXZ
	DQ	FLAT:?__hasVuDeprecated@AudioEffect@@UEAAX_N@Z
	DQ	FLAT:?__hasClipDeprecated@AudioEffect@@UEAAX_N@Z
	DQ	FLAT:?__canMonoDeprecated@AudioEffect@@UEAAX_N@Z
	DQ	FLAT:?__setRealtimeQualitiesDeprecated@AudioEffect@@UEAAXH@Z
	DQ	FLAT:?__setOfflineQualitiesDeprecated@AudioEffect@@UEAAXH@Z
	DQ	FLAT:?__isInputConnectedDeprecated@AudioEffect@@UEAA_NH@Z
	DQ	FLAT:?__isOutputConnectedDeprecated@AudioEffect@@UEAA_NH@Z
	DQ	FLAT:?canParameterBeAutomated@AudioEffectX@@UEAA_NH@Z
	DQ	FLAT:?string2parameter@AudioEffectX@@UEAA_NHPEAD@Z
	DQ	FLAT:?getParameterProperties@AudioEffectX@@UEAA_NHPEAUVstParameterProperties@@@Z
	DQ	FLAT:?beginEdit@AudioEffectX@@UEAA_NH@Z
	DQ	FLAT:?endEdit@AudioEffectX@@UEAA_NH@Z
	DQ	FLAT:?getProgramNameIndexed@Shimmer@@UEAA_NHHPEAD@Z
	DQ	FLAT:?beginSetProgram@AudioEffectX@@UEAA_NXZ
	DQ	FLAT:?endSetProgram@AudioEffectX@@UEAA_NXZ
	DQ	FLAT:?beginLoadBank@AudioEffectX@@UEAAHPEAUVstPatchChunkInfo@@@Z
	DQ	FLAT:?beginLoadProgram@AudioEffectX@@UEAAHPEAUVstPatchChunkInfo@@@Z
	DQ	FLAT:?ioChanged@AudioEffectX@@UEAA_NXZ
	DQ	FLAT:?updateSampleRate@AudioEffectX@@UEAANXZ
	DQ	FLAT:?updateBlockSize@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getInputLatency@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getOutputLatency@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getInputProperties@AudioEffectX@@UEAA_NHPEAUVstPinProperties@@@Z
	DQ	FLAT:?getOutputProperties@AudioEffectX@@UEAA_NHPEAUVstPinProperties@@@Z
	DQ	FLAT:?setSpeakerArrangement@AudioEffectX@@UEAA_NPEAUVstSpeakerArrangement@@0@Z
	DQ	FLAT:?getSpeakerArrangement@AudioEffectX@@UEAA_NPEAPEAUVstSpeakerArrangement@@0@Z
	DQ	FLAT:?setBypass@AudioEffectX@@UEAA_N_N@Z
	DQ	FLAT:?setPanLaw@AudioEffectX@@UEAA_NHM@Z
	DQ	FLAT:?setProcessPrecision@AudioEffectX@@UEAA_NH@Z
	DQ	FLAT:?getNumMidiInputChannels@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getNumMidiOutputChannels@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getTimeInfo@AudioEffectX@@UEAAPEAUVstTimeInfo@@H@Z
	DQ	FLAT:?getCurrentProcessLevel@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getAutomationState@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?processEvents@AudioEffectX@@UEAAHPEAUVstEvents@@@Z
	DQ	FLAT:?startProcess@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?stopProcess@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?processVariableIo@AudioEffectX@@UEAA_NPEAUVstVariableIo@@@Z
	DQ	FLAT:?setTotalSampleToProcess@AudioEffectX@@UEAAHH@Z
	DQ	FLAT:?getHostVendorString@AudioEffectX@@UEAA_NPEAD@Z
	DQ	FLAT:?getHostProductString@AudioEffectX@@UEAA_NPEAD@Z
	DQ	FLAT:?getHostVendorVersion@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?hostVendorSpecific@AudioEffectX@@UEAA_JH_JPEAXM@Z
	DQ	FLAT:?canHostDo@AudioEffectX@@UEAAHPEAD@Z
	DQ	FLAT:?getHostLanguage@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?isSynth@AudioEffectX@@UEAAX_N@Z
	DQ	FLAT:?noTail@AudioEffectX@@UEAAX_N@Z
	DQ	FLAT:?getGetTailSize@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getDirectory@AudioEffectX@@UEAAPEAXXZ
	DQ	FLAT:?getEffectName@Shimmer@@UEAA_NPEAD@Z
	DQ	FLAT:?getVendorString@Shimmer@@UEAA_NPEAD@Z
	DQ	FLAT:?getProductString@AudioEffectX@@UEAA_NPEAD@Z
	DQ	FLAT:?getVendorVersion@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?vendorSpecific@AudioEffectX@@UEAA_JH_JPEAXM@Z
	DQ	FLAT:?canDo@AudioEffectX@@UEAAHPEAD@Z
	DQ	FLAT:?getVstVersion@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?getPlugCategory@AudioEffectX@@UEAA?AW4VstPlugCategory@@XZ
	DQ	FLAT:?getMidiProgramName@AudioEffectX@@UEAAHHPEAUMidiProgramName@@@Z
	DQ	FLAT:?getCurrentMidiProgram@AudioEffectX@@UEAAHHPEAUMidiProgramName@@@Z
	DQ	FLAT:?getMidiProgramCategory@AudioEffectX@@UEAAHHPEAUMidiProgramCategory@@@Z
	DQ	FLAT:?hasMidiProgramsChanged@AudioEffectX@@UEAA_NH@Z
	DQ	FLAT:?getMidiKeyName@AudioEffectX@@UEAA_NHPEAUMidiKeyName@@@Z
	DQ	FLAT:?updateDisplay@AudioEffectX@@UEAA_NXZ
	DQ	FLAT:?sizeWindow@AudioEffectX@@UEAA_NHH@Z
	DQ	FLAT:?openFileSelector@AudioEffectX@@UEAA_NPEAUVstFileSelect@@@Z
	DQ	FLAT:?closeFileSelector@AudioEffectX@@UEAA_NPEAUVstFileSelect@@@Z
	DQ	FLAT:?getNextShellPlugin@AudioEffectX@@UEAAHPEAD@Z
	DQ	FLAT:?allocateArrangement@AudioEffectX@@UEAA_NPEAPEAUVstSpeakerArrangement@@H@Z
	DQ	FLAT:?deallocateArrangement@AudioEffectX@@UEAA_NPEAPEAUVstSpeakerArrangement@@@Z
	DQ	FLAT:?copySpeaker@AudioEffectX@@UEAA_NPEAUVstSpeakerProperties@@0@Z
	DQ	FLAT:?matchArrangement@AudioEffectX@@UEAA_NPEAPEAUVstSpeakerArrangement@@PEAU2@@Z
	DQ	FLAT:?offlineRead@AudioEffectX@@UEAA_NPEAUVstOfflineTask@@W4VstOfflineOption@@_N@Z
	DQ	FLAT:?offlineWrite@AudioEffectX@@UEAA_NPEAUVstOfflineTask@@W4VstOfflineOption@@@Z
	DQ	FLAT:?offlineStart@AudioEffectX@@UEAA_NPEAUVstAudioFile@@HH@Z
	DQ	FLAT:?offlineGetCurrentPass@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?offlineGetCurrentMetaPass@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?offlineNotify@AudioEffectX@@UEAA_NPEAUVstAudioFile@@H_N@Z
	DQ	FLAT:?offlinePrepare@AudioEffectX@@UEAA_NPEAUVstOfflineTask@@H@Z
	DQ	FLAT:?offlineRun@AudioEffectX@@UEAA_NPEAUVstOfflineTask@@H@Z
	DQ	FLAT:?offlineGetNumPasses@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?offlineGetNumMetaPasses@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?__wantEventsDeprecated@AudioEffectX@@UEAAXH@Z
	DQ	FLAT:?__tempoAtDeprecated@AudioEffectX@@UEAAHH@Z
	DQ	FLAT:?__getNumAutomatableParametersDeprecated@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?__getParameterQuantizationDeprecated@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?__getNumCategoriesDeprecated@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?__copyProgramDeprecated@AudioEffectX@@UEAA_NH@Z
	DQ	FLAT:?__needIdleDeprecated@AudioEffectX@@UEAA_NXZ
	DQ	FLAT:?__getPreviousPlugDeprecated@AudioEffectX@@UEAAPEAUAEffect@@H@Z
	DQ	FLAT:?__getNextPlugDeprecated@AudioEffectX@@UEAAPEAUAEffect@@H@Z
	DQ	FLAT:?__inputConnectedDeprecated@AudioEffectX@@UEAAXH_N@Z
	DQ	FLAT:?__outputConnectedDeprecated@AudioEffectX@@UEAAXH_N@Z
	DQ	FLAT:?__willProcessReplacingDeprecated@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?__wantAsyncOperationDeprecated@AudioEffectX@@UEAAX_N@Z
	DQ	FLAT:?__hasExternalBufferDeprecated@AudioEffectX@@UEAAX_N@Z
	DQ	FLAT:?__reportCurrentPositionDeprecated@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?__reportDestinationBufferDeprecated@AudioEffectX@@UEAAPEAMXZ
	DQ	FLAT:?__setOutputSamplerateDeprecated@AudioEffectX@@UEAAXM@Z
	DQ	FLAT:?__getInputSpeakerArrangementDeprecated@AudioEffectX@@UEAAPEAUVstSpeakerArrangement@@XZ
	DQ	FLAT:?__getOutputSpeakerArrangementDeprecated@AudioEffectX@@UEAAPEAUVstSpeakerArrangement@@XZ
	DQ	FLAT:?__openWindowDeprecated@AudioEffectX@@UEAAPEAXPEAU__VstWindowDeprecated@@@Z
	DQ	FLAT:?__closeWindowDeprecated@AudioEffectX@@UEAA_NPEAU__VstWindowDeprecated@@@Z
	DQ	FLAT:?__setBlockSizeAndSampleRateDeprecated@AudioEffectX@@UEAAXHM@Z
	DQ	FLAT:?__getErrorTextDeprecated@AudioEffectX@@UEAA_NPEAD@Z
	DQ	FLAT:?__getIconDeprecated@AudioEffectX@@UEAAPEAXXZ
	DQ	FLAT:?__setViewPositionDeprecated@AudioEffectX@@UEAA_NHH@Z
	DQ	FLAT:?__fxIdleDeprecated@AudioEffectX@@UEAAHXZ
	DQ	FLAT:?__keysRequiredDeprecated@AudioEffectX@@UEAA_NXZ
	DQ	FLAT:?__getChunkFileDeprecated@AudioEffectX@@UEAA_NPEAX@Z
CONST	ENDS
;	COMDAT ??_R0?AVPSMVocoder@@@8
data$rs	SEGMENT
??_R0?AVPSMVocoder@@@8 DQ FLAT:??_7type_info@@6B@	; PSMVocoder `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVPSMVocoder@@', 00H
data$rs	ENDS
;	COMDAT ??_C@_09KHHOPKD@Fox?5Suite@
CONST	SEGMENT
??_C@_09KHHOPKD@Fox?5Suite@ DB 'Fox Suite', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06LAKOKBGJ@Wobbly@
CONST	SEGMENT
??_C@_06LAKOKBGJ@Wobbly@ DB 'Wobbly', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08FBELJDCF@Metallic@
CONST	SEGMENT
??_C@_08FBELJDCF@Metallic@ DB 'Metallic', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05BCAGPPBA@Short@
CONST	SEGMENT
??_C@_05BCAGPPBA@Short@ DB 'Short', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_06PIIHCPLG@Dreamy@
CONST	SEGMENT
??_C@_06PIIHCPLG@Dreamy@ DB 'Dreamy', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07MCAEODGB@Default@
CONST	SEGMENT
??_C@_07MCAEODGB@Default@ DB 'Default', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@HACKHIPL@Enab?5MSRev@
CONST	SEGMENT
??_C@_0L@HACKHIPL@Enab?5MSRev@ DB 'Enab MSRev', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@NKCEPMPP@Enab?5PShift@
CONST	SEGMENT
??_C@_0M@NKCEPMPP@Enab?5PShift@ DB 'Enab PShift', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@LMBMODJO@Enab?5BRRev@
CONST	SEGMENT
??_C@_0L@LMBMODJO@Enab?5BRRev@ DB 'Enab BRRev', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@HJEDBBAG@Enab?5BRDel@
CONST	SEGMENT
??_C@_0L@HJEDBBAG@Enab?5BRDel@ DB 'Enab BRDel', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@OEGDAACC@Delay?5Leng@
CONST	SEGMENT
??_C@_0L@OEGDAACC@Delay?5Leng@ DB 'Delay Leng', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_08GPJFBMJO@Delay?5FB@
CONST	SEGMENT
??_C@_08GPJFBMJO@Delay?5FB@ DB 'Delay FB', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@FMLEOGHL@Delay?5Damp@
CONST	SEGMENT
??_C@_0L@FMLEOGHL@Delay?5Damp@ DB 'Delay Damp', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09ONNCCMEP@Intervals@
CONST	SEGMENT
??_C@_09ONNCCMEP@Intervals@ DB 'Intervals', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06LMOCGFEA@Spread@
CONST	SEGMENT
??_C@_06LMOCGFEA@Spread@ DB 'Spread', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_04HIAEEHII@Damp@
CONST	SEGMENT
??_C@_04HIAEEHII@Damp@ DB 'Damp', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05BFFNNFFO@Decay@
CONST	SEGMENT
??_C@_05BFFNNFFO@Decay@ DB 'Decay', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_07CNCNAGDO@Shimmer@
CONST	SEGMENT
??_C@_07CNCNAGDO@Shimmer@ DB 'Shimmer', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_03INCOKCMB@Wet@
CONST	SEGMENT
??_C@_03INCOKCMB@Wet@ DB 'Wet', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_07DOAOMMKG@Enabled@
CONST	SEGMENT
??_C@_07DOAOMMKG@Enabled@ DB 'Enabled', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08JGILNPHN@Disabled@
CONST	SEGMENT
??_C@_08JGILNPHN@Disabled@ DB 'Disabled', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_02EEKDFEKL@ms@
CONST	SEGMENT
??_C@_02EEKDFEKL@ms@ DB 'ms', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_01LKDEMHDF@s@
CONST	SEGMENT
??_C@_01LKDEMHDF@s@ DB 's', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_07FEMGBGFB@1?$CL2?5Oct@
CONST	SEGMENT
??_C@_07FEMGBGFB@1?$CL2?5Oct@ DB '1+2 Oct', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07EOOPKDLB@1?5Oct?$CL5@
CONST	SEGMENT
??_C@_07EOOPKDLB@1?5Oct?$CL5@ DB '1 Oct+5', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07JNPNFIPA@1st?5Oct@
CONST	SEGMENT
??_C@_07JNPNFIPA@1st?5Oct@ DB '1st Oct', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07JHONIOCD@7th?5Maj@
CONST	SEGMENT
??_C@_07JHONIOCD@7th?5Maj@ DB '7th Maj', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07FLEHIOLN@6th?5Maj@
CONST	SEGMENT
??_C@_07FLEHIOLN@6th?5Maj@ DB '6th Maj', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07PCKJDGJJ@5th?5Per@
CONST	SEGMENT
??_C@_07PCKJDGJJ@5th?5Per@ DB '5th Per', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07DOADDGAH@4th?5Per@
CONST	SEGMENT
??_C@_07DOADDGAH@4th?5Per@ DB '4th Per', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07HLFHFJI@3rd?5Maj@
CONST	SEGMENT
??_C@_07HLFHFJI@3rd?5Maj@ DB '3rd Maj', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07GNMKOBCE@3rd?5Min@
CONST	SEGMENT
??_C@_07GNMKOBCE@3rd?5Min@ DB '3rd Min', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07GLGBIDLM@2nd?5Maj@
CONST	SEGMENT
??_C@_07GLGBIDLM@2nd?5Maj@ DB '2nd Maj', 00H		; `string'
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
	ORG $+3
?INTERVALS_IN_SEMITONES_PITCH1@@3QBMB DD 040000000r ; 2	; INTERVALS_IN_SEMITONES_PITCH1
	DD	040400000r			; 3
	DD	040800000r			; 4
	DD	040a00000r			; 5
	DD	040e00000r			; 7
	DD	041100000r			; 9
	DD	041300000r			; 11
	DD	041400000r			; 12
	DD	041400000r			; 12
	DD	041400000r			; 12
?INTERVALS_IN_SEMITONES_PITCH2@@3QBMB DD 000000000r ; 0	; INTERVALS_IN_SEMITONES_PITCH2
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	041980000r			; 19
	DD	041c00000r			; 24
	ORG $+8
?INTERVALS_NAMES_STRING@@3PAPEADA DQ FLAT:??_C@_07GLGBIDLM@2nd?5Maj@ ; INTERVALS_NAMES_STRING
	DQ	FLAT:??_C@_07GNMKOBCE@3rd?5Min@
	DQ	FLAT:??_C@_07HLFHFJI@3rd?5Maj@
	DQ	FLAT:??_C@_07DOADDGAH@4th?5Per@
	DQ	FLAT:??_C@_07PCKJDGJJ@5th?5Per@
	DQ	FLAT:??_C@_07FLEHIOLN@6th?5Maj@
	DQ	FLAT:??_C@_07JHONIOCD@7th?5Maj@
	DQ	FLAT:??_C@_07JNPNFIPA@1st?5Oct@
	DQ	FLAT:??_C@_07EOOPKDLB@1?5Oct?$CL5@
	DQ	FLAT:??_C@_07FEMGBGFB@1?$CL2?5Oct@
PUBLIC	??_GPSMVocoder@@QEAAPEAXI@Z			; PSMVocoder::`scalar deleting destructor'
PUBLIC	??_GFreeverb@@QEAAPEAXI@Z			; Freeverb::`scalar deleting destructor'
PUBLIC	??1Shimmer@@UEAA@XZ				; Shimmer::~Shimmer
PUBLIC	?getVendorString@Shimmer@@UEAA_NPEAD@Z		; Shimmer::getVendorString
PUBLIC	?getEffectName@Shimmer@@UEAA_NPEAD@Z		; Shimmer::getEffectName
PUBLIC	?getProgramNameIndexed@Shimmer@@UEAA_NHHPEAD@Z	; Shimmer::getProgramNameIndexed
PUBLIC	?getProgramName@Shimmer@@UEAAXPEAD@Z		; Shimmer::getProgramName
PUBLIC	?setProgram@Shimmer@@UEAAXH@Z			; Shimmer::setProgram
PUBLIC	?InitPresets@Shimmer@@AEAAXXZ			; Shimmer::InitPresets
PUBLIC	?getParameterName@Shimmer@@UEAAXHPEAD@Z		; Shimmer::getParameterName
PUBLIC	?getParameterDisplay@Shimmer@@UEAAXHPEAD@Z	; Shimmer::getParameterDisplay
PUBLIC	?getParameterLabel@Shimmer@@UEAAXHPEAD@Z	; Shimmer::getParameterLabel
PUBLIC	?getParameter@Shimmer@@UEAAMH@Z			; Shimmer::getParameter
PUBLIC	?setParameter@Shimmer@@UEAAXHM@Z		; Shimmer::setParameter
PUBLIC	?processReplacing@Shimmer@@UEAAXPEAPEAM0H@Z	; Shimmer::processReplacing
PUBLIC	?setSampleRate@Shimmer@@UEAAXM@Z		; Shimmer::setSampleRate
PUBLIC	?InitPlugin@Shimmer@@AEAAXXZ			; Shimmer::InitPlugin
PUBLIC	??_GShimmer@@UEAAPEAXI@Z			; Shimmer::`scalar deleting destructor'
PUBLIC	??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z ; Shimmer::Shimmer
PUBLIC	?mapValueOutsideRange@@YAMMMM@Z			; mapValueOutsideRange
PUBLIC	??0IAudioSignalProcessor@@QEAA@XZ		; IAudioSignalProcessor::IAudioSignalProcessor
PUBLIC	?setParameters@PSMVocoder@@QEAAXAEBUPSMVocoderParameters@@@Z ; PSMVocoder::setParameters
PUBLIC	?getParameters@PSMVocoder@@QEAA?AUPSMVocoderParameters@@XZ ; PSMVocoder::getParameters
PUBLIC	?processAudioSample@PSMVocoder@@UEAANN@Z	; PSMVocoder::processAudioSample
PUBLIC	?findPeaksAndRegionsOfInfluence@PSMVocoder@@QEAAXXZ ; PSMVocoder::findPeaksAndRegionsOfInfluence
PUBLIC	?findPreviousNearestPeak@PSMVocoder@@QEAAHH@Z	; PSMVocoder::findPreviousNearestPeak
PUBLIC	?setPitchShift@PSMVocoder@@QEAAXN@Z		; PSMVocoder::setPitchShift
PUBLIC	?canProcessAudioFrame@PSMVocoder@@UEAA_NXZ	; PSMVocoder::canProcessAudioFrame
PUBLIC	?reset@PSMVocoder@@UEAA_NN@Z			; PSMVocoder::reset
PUBLIC	??1PSMVocoder@@QEAA@XZ				; PSMVocoder::~PSMVocoder
PUBLIC	??0PSMVocoder@@QEAA@XZ				; PSMVocoder::PSMVocoder
PUBLIC	?getIFFTData@PhaseVocoder@@QEAAPEAY01NXZ	; PhaseVocoder::getIFFTData
PUBLIC	?getFFTData@PhaseVocoder@@QEAAPEAY01NXZ		; PhaseVocoder::getFFTData
PUBLIC	??1PhaseVocoder@@QEAA@XZ			; PhaseVocoder::~PhaseVocoder
PUBLIC	??0PhaseVocoder@@QEAA@XZ			; PhaseVocoder::PhaseVocoder
PUBLIC	?reset@BinData@@QEAAXXZ				; BinData::reset
PUBLIC	??4BinData@@QEAAAEAU0@AEBU0@@Z			; BinData::operator=
PUBLIC	??0BinData@@QEAA@XZ				; BinData::BinData
PUBLIC	??4PSMVocoderParameters@@QEAAAEAU0@AEBU0@@Z	; PSMVocoderParameters::operator=
PUBLIC	??0PSMVocoderParameters@@QEAA@XZ		; PSMVocoderParameters::PSMVocoderParameters
PUBLIC	?processAudioFrame@IAudioSignalProcessor@@UEAA_NPEBMPEAMII@Z ; IAudioSignalProcessor::processAudioFrame
PUBLIC	?processAuxInputAudioSample@IAudioSignalProcessor@@UEAANN@Z ; IAudioSignalProcessor::processAuxInputAudioSample
PUBLIC	?enableAuxInput@IAudioSignalProcessor@@UEAAX_N@Z ; IAudioSignalProcessor::enableAuxInput
PUBLIC	?setSampleRate@IAudioSignalProcessor@@UEAAXN@Z	; IAudioSignalProcessor::setSampleRate
PUBLIC	?resample@@YA_NPEAN0IIW4interpolation@@N0@Z	; resample
PUBLIC	?doLagrangeInterpolation@@YANPEAN0HN@Z		; doLagrangeInterpolation
PUBLIC	?doLinearInterpolation@@YANNNN@Z		; doLinearInterpolation
PUBLIC	?principalArg@@YANN@Z				; principalArg
PUBLIC	?getPhase@@YANNN@Z				; getPhase
PUBLIC	?getMagnitude@@YANNN@Z				; getMagnitude
PUBLIC	?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z ; createEffectInstance
EXTRN	??_EShimmer@@UEAAPEAXI@Z:PROC			; Shimmer::`vector deleting destructor'
?kCTCorrFactorAntiLog@@3NB DQ 01H DUP (?)		; kCTCorrFactorAntiLog
?kCTCorrFactorZero@@3NB DQ 01H DUP (?)			; kCTCorrFactorZero
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GPSMVocoder@@QEAAPEAXI@Z DD imagerel $LN6@scalar
	DD	imagerel $LN6@scalar+23
	DD	imagerel $unwind$??_GPSMVocoder@@QEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GFreeverb@@QEAAPEAXI@Z DD imagerel $LN6@scalar
	DD	imagerel $LN6@scalar+23
	DD	imagerel $unwind$??_GFreeverb@@QEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1Shimmer@@UEAA@XZ DD imagerel $LN38@Shimmer
	DD	imagerel $LN38@Shimmer+140
	DD	imagerel $unwind$??1Shimmer@@UEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?getVendorString@Shimmer@@UEAA_NPEAD@Z DD imagerel $LN6@getVendorS
	DD	imagerel $LN6@getVendorS+43
	DD	imagerel $unwind$?getVendorString@Shimmer@@UEAA_NPEAD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?getEffectName@Shimmer@@UEAA_NPEAD@Z DD imagerel $LN6@getEffectN
	DD	imagerel $LN6@getEffectN+43
	DD	imagerel $unwind$?getEffectName@Shimmer@@UEAA_NPEAD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?getProgramNameIndexed@Shimmer@@UEAA_NHHPEAD@Z DD imagerel $LN5@getProgram
	DD	imagerel $LN5@getProgram+51
	DD	imagerel $unwind$?getProgramNameIndexed@Shimmer@@UEAA_NHHPEAD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?setProgram@Shimmer@@UEAAXH@Z DD imagerel $LN4@setProgram
	DD	imagerel $LN4@setProgram+137
	DD	imagerel $unwind$?setProgram@Shimmer@@UEAAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?InitPresets@Shimmer@@AEAAXXZ DD imagerel $LN4@InitPreset
	DD	imagerel $LN4@InitPreset+597
	DD	imagerel $unwind$?InitPresets@Shimmer@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?getParameterName@Shimmer@@UEAAXHPEAD@Z DD imagerel $LN48@getParamet
	DD	imagerel $LN48@getParamet+222
	DD	imagerel $unwind$?getParameterName@Shimmer@@UEAAXHPEAD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?getParameterDisplay@Shimmer@@UEAAXHPEAD@Z DD imagerel $LN55@getParamet
	DD	imagerel $LN55@getParamet+374
	DD	imagerel $unwind$?getParameterDisplay@Shimmer@@UEAAXHPEAD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?getParameterLabel@Shimmer@@UEAAXHPEAD@Z DD imagerel $LN50@getParamet
	DD	imagerel $LN50@getParamet+136
	DD	imagerel $unwind$?getParameterLabel@Shimmer@@UEAAXHPEAD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?setParameter@Shimmer@@UEAAXHM@Z DD imagerel $LN47
	DD	imagerel $LN47+797
	DD	imagerel $unwind$?setParameter@Shimmer@@UEAAXHM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processReplacing@Shimmer@@UEAAXPEAPEAM0H@Z DD imagerel $LN16@processRep
	DD	imagerel $LN16@processRep+601
	DD	imagerel $unwind$?processReplacing@Shimmer@@UEAAXPEAPEAM0H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?setSampleRate@Shimmer@@UEAAXM@Z DD imagerel $LN4@setSampleR
	DD	imagerel $LN4@setSampleR+153
	DD	imagerel $unwind$?setSampleRate@Shimmer@@UEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?InitPlugin@Shimmer@@AEAAXXZ DD imagerel $LN67@InitPlugin
	DD	imagerel $LN67@InitPlugin+992
	DD	imagerel $unwind$?InitPlugin@Shimmer@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$0@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DD imagerel ?dtor$0@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DD	imagerel ?dtor$0@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA+32
	DD	imagerel $unwind$?dtor$0@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$1@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DD imagerel ?dtor$1@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DD	imagerel ?dtor$1@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA+32
	DD	imagerel $unwind$?dtor$1@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$2@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DD imagerel ?dtor$2@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DD	imagerel ?dtor$2@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA+32
	DD	imagerel $unwind$?dtor$2@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$3@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DD imagerel ?dtor$3@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DD	imagerel ?dtor$3@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA+32
	DD	imagerel $unwind$?dtor$3@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$4@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DD imagerel ?dtor$4@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DD	imagerel ?dtor$4@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA+32
	DD	imagerel $unwind$?dtor$4@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$5@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DD imagerel ?dtor$5@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DD	imagerel ?dtor$5@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA+32
	DD	imagerel $unwind$?dtor$5@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$6@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DD imagerel ?dtor$6@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DD	imagerel ?dtor$6@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA+32
	DD	imagerel $unwind$?dtor$6@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GShimmer@@UEAAPEAXI@Z DD imagerel $LN6@scalar
	DD	imagerel $LN6@scalar+52
	DD	imagerel $unwind$??_GShimmer@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DD imagerel $LN14@Shimmer
	DD	imagerel $LN14@Shimmer+265
	DD	imagerel $unwind$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?setParameters@PSMVocoder@@QEAAXAEBUPSMVocoderParameters@@@Z DD imagerel $LN8@setParamet
	DD	imagerel $LN8@setParamet+66
	DD	imagerel $unwind$?setParameters@PSMVocoder@@QEAAXAEBUPSMVocoderParameters@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processAudioSample@PSMVocoder@@UEAANN@Z DD imagerel $LN161@processAud
	DD	imagerel $LN161@processAud+1735
	DD	imagerel $unwind$?processAudioSample@PSMVocoder@@UEAANN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?findPeaksAndRegionsOfInfluence@PSMVocoder@@QEAAXXZ DD imagerel $LN88@findPeaksA
	DD	imagerel $LN88@findPeaksA+758
	DD	imagerel $unwind$?findPeaksAndRegionsOfInfluence@PSMVocoder@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?findPreviousNearestPeak@PSMVocoder@@QEAAHH@Z DD imagerel $LN20@findPrevio
	DD	imagerel $LN20@findPrevio+132
	DD	imagerel $unwind$?findPreviousNearestPeak@PSMVocoder@@QEAAHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?setPitchShift@PSMVocoder@@QEAAXN@Z DD imagerel $LN14@setPitchSh
	DD	imagerel $LN14@setPitchSh+459
	DD	imagerel $unwind$?setPitchShift@PSMVocoder@@QEAAXN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?reset@PSMVocoder@@UEAA_NN@Z DD imagerel $LN16@reset
	DD	imagerel $LN16@reset+222
	DD	imagerel $unwind$?reset@PSMVocoder@@UEAA_NN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1PSMVocoder@@QEAA@XZ DD imagerel $LN12@PSMVocoder
	DD	imagerel $LN12@PSMVocoder+109
	DD	imagerel $unwind$??1PSMVocoder@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0PSMVocoder@@QEAA@XZ DD imagerel $LN34@PSMVocoder
	DD	imagerel $LN34@PSMVocoder+429
	DD	imagerel $unwind$??0PSMVocoder@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1PhaseVocoder@@QEAA@XZ DD imagerel $LN8@PhaseVocod
	DD	imagerel $LN8@PhaseVocod+64
	DD	imagerel $unwind$??1PhaseVocoder@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?resample@@YA_NPEAN0IIW4interpolation@@N0@Z DD imagerel $LN94@resample
	DD	imagerel $LN94@resample+315
	DD	imagerel $unwind$?resample@@YA_NPEAN0IIW4interpolation@@N0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?principalArg@@YANN@Z DD imagerel $LN6@principalA
	DD	imagerel $LN6@principalA+79
	DD	imagerel $unwind$?principalArg@@YANN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__EkCTCorrFactorAntiLog@@YAXXZ DD imagerel ??__EkCTCorrFactorAntiLog@@YAXXZ
	DD	imagerel ??__EkCTCorrFactorAntiLog@@YAXXZ+47
	DD	imagerel $unwind$??__EkCTCorrFactorAntiLog@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__EkCTCorrFactorZero@@YAXXZ DD imagerel ??__EkCTCorrFactorZero@@YAXXZ
	DD	imagerel ??__EkCTCorrFactorZero@@YAXXZ+39
	DD	imagerel $unwind$??__EkCTCorrFactorZero@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DD imagerel $LN8@createEffe
	DD	imagerel $LN8@createEffe+42
	DD	imagerel $unwind$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$0@?0??createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z@4HA DD imagerel ?dtor$0@?0??createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z@4HA
	DD	imagerel ?dtor$0@?0??createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z@4HA+29
	DD	imagerel $unwind$?dtor$0@?0??createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z@4HA
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$0@?0??createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DD 020001c04H
	DB	02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DW 0e02H
	DD	imagerel ?dtor$0@?0??createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DB 028H
	DD	imagerel $stateUnwindMap$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
	DD	imagerel $ip2state$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DQ 03002320600020611r ; 1.96423e-77
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?createEffectInstance@@YAPEAVAudioEffect@@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__EkCTCorrFactorZero@@YAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__EkCTCorrFactorAntiLog@@YAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?principalArg@@YANN@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?resample@@YA_NPEAN0IIW4interpolation@@N0@Z DQ 00003740f00060f01r ; 4.80248e-309
	DQ	0000134050002640ar		; 1.67326e-309
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1PhaseVocoder@@QEAA@XZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0PSMVocoder@@QEAA@XZ DD 02063d02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0PSMVocoder@@QEAA@XZ DW 0e02H
	DD	imagerel ?dtor$0@?0???0PSMVocoder@@QEAA@XZ@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??0PSMVocoder@@QEAA@XZ DB 028H
	DD	imagerel $stateUnwindMap$??0PSMVocoder@@QEAA@XZ
	DD	imagerel $ip2state$??0PSMVocoder@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0PSMVocoder@@QEAA@XZ DQ 00009641800081811r ; 1.30598e-308
	DQ	00007341800085418r		; 1.00177e-308
	DD	070143218H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??0PSMVocoder@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1PSMVocoder@@QEAA@XZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?reset@PSMVocoder@@UEAA_NN@Z DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?setPitchShift@PSMVocoder@@QEAAXN@Z DQ 000028830000c3001r ; 3.52115e-309
	DQ	0000468270003782br		; 6.12847e-309
	DQ	0000c3410000d5410r		; 1.69709e-308
	DD	0700c9210H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?findPreviousNearestPeak@PSMVocoder@@QEAAHH@Z DQ 000097419000a1901r ; 1.31467e-308
	DQ	00007541900086419r		; 1.01915e-308
	DQ	0e015321900063419r		; -7.10469e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?findPeaksAndRegionsOfInfluence@PSMVocoder@@QEAAXXZ DQ 00004681e000c1e01r ; 6.12828e-309
	DQ	0f010921700123417r		; -6.43156e+231
	DQ	07008c00ad00ce00er		; 4.80313e+231
	DD	050066007H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processAudioSample@PSMVocoder@@UEAANN@Z DQ 00802d878001d7801r ; 4.45906e-270
	DQ	00804b8660803c86fr		; 4.90264e-270
	DQ	0080698540805a85dr		; 5.34622e-270
	DQ	00808783908078848r		; 5.78977e-270
	DQ	0101c64250809682dr		; 4.5718e-231
	DQ	0101a3425101b5425r		; 4.21955e-231
	DQ	0e016f01810140125r		; -7.68866e+154
	DQ	000007010c012d014r		; 6.08774e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?setParameters@PSMVocoder@@QEAAXAEBUPSMVocoderParameters@@@Z DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DD 0203d502H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DW 0c02H
	DD	imagerel ??1AudioEffectX@@UEAA@XZ
	DB	060H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DB 028H
	DD	imagerel $stateUnwindMap$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
	DD	imagerel $ip2state$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z DQ 00007340f00040f11r ; 1.00175e-308
	DD	0700b320fH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GShimmer@@UEAAPEAXI@Z DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$6@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$5@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$4@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$3@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$2@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$1@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$0@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA DQ 05002320600020601r ; 2.6336e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?InitPlugin@Shimmer@@AEAAXXZ DQ 08e001202b8002c1er ; -3.01258e-241
	DQ	02c00120692001204r		; 9.40456e-97
	DQ	02c00120a2c001208r		; 9.40459e-97
	DQ	000120e06d900120cr		; 2.51083e-308
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?InitPlugin@Shimmer@@AEAAXXZ DW 0e0eH
	DD	imagerel ?dtor$0@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DB	036H
	DD	imagerel ?dtor$1@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DB	05eH
	DD	imagerel ?dtor$2@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DB	086H
	DD	imagerel ?dtor$3@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DB	0aeH
	DD	imagerel ?dtor$4@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DB	0d6H
	DD	imagerel ?dtor$5@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
	DB	0feH
	DD	imagerel ?dtor$6@?0??InitPlugin@Shimmer@@AEAAXXZ@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?InitPlugin@Shimmer@@AEAAXXZ DB 028H
	DD	imagerel $stateUnwindMap$?InitPlugin@Shimmer@@AEAAXXZ
	DD	imagerel $ip2state$?InitPlugin@Shimmer@@AEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?InitPlugin@Shimmer@@AEAAXXZ DQ 00008681300071311r ; 1.16907e-308
	DQ	00012010f0015340fr		; 2.50378e-308
	DD	07008H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?InitPlugin@Shimmer@@AEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?setSampleRate@Shimmer@@UEAAXM@Z DQ 00002681200061201r ; 3.34668e-309
	DQ	07006520a0008340ar		; 4.33162e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processReplacing@Shimmer@@UEAAXPEAPEAM0H@Z DQ 00003a85700145701r ; 5.08649e-309
	DQ	00005884d00049852r		; 7.69378e-309
	DQ	00007684100067848r		; 1.0301e-308
	DQ	00016342600196426r		; 3.08781e-308
	DQ	0c018e01af01cf226r		; -6.21885
	DD	050157016H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?setParameter@Shimmer@@UEAAXHM@Z DD 081401H
	DD	026814H
	DD	09640fH
	DD	08340fH
	DD	0700b520fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?getParameterLabel@Shimmer@@UEAAXHPEAD@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?getParameterDisplay@Shimmer@@UEAAXHPEAD@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?getParameterName@Shimmer@@UEAAXHPEAD@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?InitPresets@Shimmer@@AEAAXXZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?setProgram@Shimmer@@UEAAXH@Z DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?getProgramNameIndexed@Shimmer@@UEAA_NHHPEAD@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?getEffectName@Shimmer@@UEAA_NPEAD@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?getVendorString@Shimmer@@UEAA_NPEAD@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1Shimmer@@UEAA@XZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GFreeverb@@QEAAPEAXI@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GPSMVocoder@@QEAAPEAXI@Z DQ 03002320600020601r ; 1.96423e-77
?kCTCorrFactorZero$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorZero@@YAXXZ ; kCTCorrFactorZero$initializer$
?kCTCorrFactorUnity$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorUnity@@YAXXZ ; kCTCorrFactorUnity$initializer$
?kCTCorrFactorAntiUnity$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorAntiUnity@@YAXXZ ; kCTCorrFactorAntiUnity$initializer$
?kCTCorrFactorAntiLog$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorAntiLog@@YAXXZ ; kCTCorrFactorAntiLog$initializer$
?kCTCorrFactorAntiLogScale$initializer$@@3P6AXXZEA DQ FLAT:??__EkCTCorrFactorAntiLogScale@@YAXXZ ; kCTCorrFactorAntiLogScale$initializer$
?MAX_LPF_FREQUENCY_LOG$initializer$@@3P6AXXZEA DQ FLAT:??__EMAX_LPF_FREQUENCY_LOG@@YAXXZ ; MAX_LPF_FREQUENCY_LOG$initializer$
?MIN_LPF_FREQUENCY_LOG$initializer$@@3P6AXXZEA DQ FLAT:??__EMIN_LPF_FREQUENCY_LOG@@YAXXZ ; MIN_LPF_FREQUENCY_LOG$initializer$
?MAX_HPF_FREQUENCY_LOG$initializer$@@3P6AXXZEA DQ FLAT:??__EMAX_HPF_FREQUENCY_LOG@@YAXXZ ; MAX_HPF_FREQUENCY_LOG$initializer$
?MIN_HPF_FREQUENCY_LOG$initializer$@@3P6AXXZEA DQ FLAT:??__EMIN_HPF_FREQUENCY_LOG@@YAXXZ ; MIN_HPF_FREQUENCY_LOG$initializer$
?MAX_FREQUENCY_LOG$initializer$@@3P6AXXZEA DQ FLAT:??__EMAX_FREQUENCY_LOG@@YAXXZ ; MAX_FREQUENCY_LOG$initializer$
?MIN_FREQUENCY_LOG$initializer$@@3P6AXXZEA DQ FLAT:??__EMIN_FREQUENCY_LOG@@YAXXZ ; MIN_FREQUENCY_LOG$initializer$
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
; File E:\FoxSuite\fox-suite-blocks\include\utils.h
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp
; File E:\FoxSuite\fox-suite-blocks\include\utils.h
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp
; File E:\FoxSuite\fox-suite-blocks\include\utils.h
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
; File E:\FoxSuite\fox-suite-blocks\include\utils.h
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
; File E:\FoxSuite\fox-suite-blocks\include\utils.h
; File E:\FoxSuite\fox-suite-blocks\src\LPCombFilter.cpp
; File E:\FoxSuite\fox-suite-blocks\src\LPFButterworth.cpp
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
; File E:\FoxSuite\fox-suite-blocks\include\utils.h
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp
;	COMDAT ?setParameter@Shimmer@@UEAAXHM@Z
_TEXT	SEGMENT
this$ = 64
index$ = 72
value$ = 80
?setParameter@Shimmer@@UEAAXHM@Z PROC			; Shimmer::setParameter, COMDAT

; 221  : {

$LN47:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	movaps	XMMWORD PTR [rsp+32], xmm6
	mov	rdi, rcx

; 222  :     switch (index) {

	cmp	edx, 6
	jg	$LN20@setParamet
	je	$LN11@setParamet
	test	edx, edx
	je	$LN4@setParamet
	sub	edx, 1
	je	$LN5@setParamet
	sub	edx, 1
	je	$LN9@setParamet
	sub	edx, 1
	je	$LN6@setParamet
	sub	edx, 1
	je	$LN7@setParamet
	cmp	edx, 1
	jne	$LN18@setParamet

; 251  :         BranchReverb->setReverbSpread(shim_spread);

	mov	rax, QWORD PTR [rcx+304]
; File E:\FoxSuite\fox-suite-blocks\include\utils.h

; 23   :     return minvalue + value * (maxValue - minvalue);

	movss	xmm4, DWORD PTR __real@3f800000
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp

; 281  :     wet1 = freeverb_wet * (width / 2.0 + 0.5);

	movss	xmm3, DWORD PTR __real@3f000000

; 282  :     wet2 = freeverb_wet * (1 - width) / 2.0;

	movaps	xmm1, xmm4
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp

; 250  :         shim_spread = value;

	movss	DWORD PTR [rcx+268], xmm2
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp

; 213  :     freeverb_spread = spread;

	movss	DWORD PTR [rax+20], xmm2
; File E:\FoxSuite\fox-suite-blocks\include\utils.h

; 23   :     return minvalue + value * (maxValue - minvalue);

	addss	xmm2, xmm2
	subss	xmm2, xmm4
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp

; 281  :     wet1 = freeverb_wet * (width / 2.0 + 0.5);

	movaps	xmm0, xmm2
	addss	xmm0, xmm4
	mulss	xmm0, xmm3
	mulss	xmm0, DWORD PTR [rax]
	movss	DWORD PTR [rax+24], xmm0

; 282  :     wet2 = freeverb_wet * (1 - width) / 2.0;

	movaps	xmm0, xmm4
	subss	xmm0, xmm2
	mulss	xmm0, DWORD PTR [rax]
	mulss	xmm0, xmm3
	movss	DWORD PTR [rax+28], xmm0

; 283  :     dry = (1.0 - freeverb_wet);

	movaps	xmm0, xmm4
	subss	xmm0, DWORD PTR [rax]
	movss	DWORD PTR [rax+32], xmm0
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp

; 252  :         MasterReverb->setReverbSpread(shim_spread);

	mov	rax, QWORD PTR [rcx+312]
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp

; 213  :     freeverb_spread = spread;

	movss	xmm2, DWORD PTR [rcx+268]
	movss	DWORD PTR [rax+20], xmm2
; File E:\FoxSuite\fox-suite-blocks\include\utils.h

; 23   :     return minvalue + value * (maxValue - minvalue);

	addss	xmm2, xmm2
	subss	xmm2, xmm4
; File E:\FoxSuite\fox-suite-blocks\src\Freeverb.cpp

; 282  :     wet2 = freeverb_wet * (1 - width) / 2.0;

	subss	xmm1, xmm2
	movaps	xmm0, xmm2
	addss	xmm0, xmm4

; 283  :     dry = (1.0 - freeverb_wet);

	subss	xmm4, DWORD PTR [rax]
	mulss	xmm1, DWORD PTR [rax]
	mulss	xmm0, xmm3
	mulss	xmm1, xmm3
	mulss	xmm0, DWORD PTR [rax]
	movss	DWORD PTR [rax+28], xmm1
	movss	DWORD PTR [rax+32], xmm4
	movss	DWORD PTR [rax+24], xmm0
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp

; 253  :         break;

	jmp	$LN18@setParamet
$LN7@setParamet:

; 239  :     }    
; 240  :     case Param_damping:
; 241  :     {
; 242  :         shim_damping = value;
; 243  :         float dampingFrequency = mapValueIntoRange(1.0 - shim_damping, MIN_LPF_FREQUENCY, MAX_LPF_FREQUENCY);

	movss	xmm6, DWORD PTR __real@3f800000
	subss	xmm6, xmm2
	movss	DWORD PTR [rcx+264], xmm2

; 244  :         BranchReverb->setReverbDampingFrequency(dampingFrequency);

	mov	rcx, QWORD PTR [rcx+304]
; File E:\FoxSuite\fox-suite-blocks\include\utils.h

; 23   :     return minvalue + value * (maxValue - minvalue);

	mulss	xmm6, DWORD PTR __real@46944800
	addss	xmm6, DWORD PTR __real@41a00000
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp

; 244  :         BranchReverb->setReverbDampingFrequency(dampingFrequency);

	movaps	xmm1, xmm6
	call	?setReverbDampingFrequency@Freeverb@@QEAAXM@Z ; Freeverb::setReverbDampingFrequency

; 245  :         MasterReverb->setReverbDampingFrequency(dampingFrequency);

	mov	rcx, QWORD PTR [rdi+312]
	movaps	xmm1, xmm6
	call	?setReverbDampingFrequency@Freeverb@@QEAAXM@Z ; Freeverb::setReverbDampingFrequency

; 246  :         break;

	jmp	$LN18@setParamet
$LN6@setParamet:

; 232  :     }
; 233  :     case Param_decay:
; 234  :     {
; 235  :         shim_decay = value * MAX_REVERB_DECAY_IN_SECONDS;

	mulss	xmm2, DWORD PTR __real@41700000
	movss	DWORD PTR [rcx+260], xmm2

; 236  :         //BranchReverb->setReverbDecayInSeconds(shim_decay);
; 237  :         MasterReverb->setReverbDecayInSeconds(shim_decay);

	movaps	xmm1, xmm2
	mov	rcx, QWORD PTR [rcx+312]
	call	?setReverbDecayInSeconds@Freeverb@@QEAAXM@Z ; Freeverb::setReverbDecayInSeconds

; 238  :         break;

	jmp	$LN18@setParamet
$LN9@setParamet:

; 254  :     }
; 255  :     case Param_shimIntrvals:
; 256  :     {        
; 257  :         if (value == 1)

	ucomiss	xmm2, DWORD PTR __real@3f800000
	jne	SHORT $LN10@setParamet

; 258  :             value = 0.99; // if value = 1, then pitIdx = NUM_OF_PITCH_INTRVL_ALLOWED + 1 -> outside of array boundaries

	movss	xmm2, DWORD PTR __real@3f7d70a4
$LN10@setParamet:

; 259  :         shim_intervals = value;

	movss	DWORD PTR [rcx+256], xmm2

; 260  :         int pitIdx = shim_intervals / DELTA_PARAMETER_BETWEEN_INTERVALS;
; 261  :         PitchShift_1octL->setPitchShift(INTERVALS_IN_SEMITONES_PITCH1[pitIdx]);

	lea	rsi, OFFSET FLAT:__ImageBase
	mulss	xmm2, DWORD PTR __real@41200000
	mov	rcx, QWORD PTR [rcx+320]
	cvttss2si eax, xmm2
	movsxd	rbx, eax
	movss	xmm1, DWORD PTR ?INTERVALS_IN_SEMITONES_PITCH1@@3QBMB[rsi+rbx*4]
	cvtps2pd xmm1, xmm1
	call	?setPitchShift@PSMVocoder@@QEAAXN@Z	; PSMVocoder::setPitchShift
	movss	xmm1, DWORD PTR ?INTERVALS_IN_SEMITONES_PITCH1@@3QBMB[rsi+rbx*4]

; 262  :         PitchShift_1octR->setPitchShift(INTERVALS_IN_SEMITONES_PITCH1[pitIdx]);

	mov	rcx, QWORD PTR [rdi+328]
	cvtps2pd xmm1, xmm1
	call	?setPitchShift@PSMVocoder@@QEAAXN@Z	; PSMVocoder::setPitchShift
	movss	xmm1, DWORD PTR ?INTERVALS_IN_SEMITONES_PITCH2@@3QBMB[rsi+rbx*4]

; 263  :         PitchShift_2octL->setPitchShift(INTERVALS_IN_SEMITONES_PITCH2[pitIdx]);

	mov	rcx, QWORD PTR [rdi+336]
	cvtps2pd xmm1, xmm1
	call	?setPitchShift@PSMVocoder@@QEAAXN@Z	; PSMVocoder::setPitchShift
	movss	xmm1, DWORD PTR ?INTERVALS_IN_SEMITONES_PITCH2@@3QBMB[rsi+rbx*4]

; 264  :         PitchShift_2octR->setPitchShift(INTERVALS_IN_SEMITONES_PITCH2[pitIdx]);

	mov	rcx, QWORD PTR [rdi+344]
	cvtps2pd xmm1, xmm1
	call	?setPitchShift@PSMVocoder@@QEAAXN@Z	; PSMVocoder::setPitchShift

; 265  :         break;

	jmp	$LN18@setParamet
$LN5@setParamet:

; 227  :     }
; 228  :     case Param_shimmer:
; 229  :     {
; 230  :         shim_shimmer = value;

	movss	DWORD PTR [rcx+252], xmm2

; 231  :         break;

	jmp	$LN18@setParamet
$LN4@setParamet:

; 223  :     case Param_wet:
; 224  :     {
; 225  :         shim_wet = value;        

	movss	DWORD PTR [rcx+248], xmm2

; 226  :         break;

	jmp	$LN18@setParamet
$LN11@setParamet:

; 266  :     }
; 267  : 
; 268  :     // --- DEVELOPER PARAMETERS 
; 269  :     case Param_brDelLength:
; 270  :     {
; 271  :         dev_BrDelLength = value * MAX_BRANCH_DELAY_LENGTH_MS;

	mulss	xmm2, DWORD PTR __real@43fa0000
	movss	DWORD PTR [rcx+272], xmm2

; 272  :         BranchDelay->setDelayInmsec(dev_BrDelLength);

	mov	rcx, QWORD PTR [rcx+352]
	movd	xmm0, DWORD PTR [rcx+16]
; File E:\FoxSuite\fox-suite-blocks\src\Delay.cpp

; 130  : 	if (dly_delayInmsec > dly_lineLengthInmsec)

	cvtdq2ps xmm0, xmm0
	movss	DWORD PTR [rcx+24], xmm2
	comiss	xmm2, xmm0
	jbe	SHORT $LN36@setParamet

; 131  : 		dly_delayInmsec = dly_lineLengthInmsec;

	movss	DWORD PTR [rcx+24], xmm0
$LN36@setParamet:

; 132  : 
; 133  : 	// Update parameters based on new delay length
; 134  : 	updateParameters();

	call	?updateParameters@Delay@@QEAAXXZ	; Delay::updateParameters
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp

; 273  :         break;

	jmp	$LN18@setParamet
$LN20@setParamet:

; 222  :     switch (index) {

	sub	edx, 7
	je	$LN12@setParamet
	sub	edx, 1
	je	SHORT $LN13@setParamet
	sub	edx, 1
	je	SHORT $LN16@setParamet
	sub	edx, 1
	je	SHORT $LN15@setParamet
	sub	edx, 1
	je	SHORT $LN14@setParamet
	cmp	edx, 1
	jne	$LN18@setParamet

; 301  :     }
; 302  :     case Param_enMsRev:
; 303  :     {
; 304  :         dev_enableMasterRev = value;

	movss	DWORD PTR [rcx+296], xmm2

; 305  :         break;

	jmp	SHORT $LN18@setParamet
$LN14@setParamet:

; 286  :     }
; 287  :     case Param_enBrDel:
; 288  :     {
; 289  :         dev_enableBranchDel = value;

	movss	DWORD PTR [rcx+292], xmm2

; 290  :         break;

	jmp	SHORT $LN18@setParamet
$LN15@setParamet:

; 291  :     }
; 292  :     case Param_enBrRev:
; 293  :     {
; 294  :         dev_enableBranchRev = value;

	movss	DWORD PTR [rcx+288], xmm2

; 295  :         break;

	jmp	SHORT $LN18@setParamet
$LN16@setParamet:

; 296  :     }
; 297  :     case Param_enPitch:
; 298  :     {
; 299  :         dev_enablePitchShift = value;

	movss	DWORD PTR [rcx+284], xmm2

; 300  :         break;

	jmp	SHORT $LN18@setParamet
$LN13@setParamet:

; 279  :         break;
; 280  :     }
; 281  :     case Param_brDelDamp:
; 282  :     {
; 283  :         dev_BrDelDamp = value;
; 284  :         BranchDelay->setCutoffFrequency(mapValueIntoRange(1.0-dev_BrDelDamp, MIN_LPF_FREQUENCY, MAX_LPF_FREQUENCY));

	movss	xmm0, DWORD PTR __real@3f800000
	movss	DWORD PTR [rcx+280], xmm2
	subss	xmm0, xmm2
	mov	rcx, QWORD PTR [rcx+352]
; File E:\FoxSuite\fox-suite-blocks\include\utils.h

; 23   :     return minvalue + value * (maxValue - minvalue);

	mulss	xmm0, DWORD PTR __real@46944800
	addss	xmm0, DWORD PTR __real@41a00000
; File E:\FoxSuite\fox-suite-blocks\src\LPCombFilter.cpp

; 30   : 	lpcf_cutoffFreq = cutoffFreq;

	movss	DWORD PTR [rcx+80], xmm0

; 31   : 
; 32   : 	// set LPF cutoff frequency to the inserted value
; 33   : 	lpcf_feedbackLPF->setCutoffFrequency(lpcf_cutoffFreq);

	mov	rcx, QWORD PTR [rcx+72]
; File E:\FoxSuite\fox-suite-blocks\src\LPFButterworth.cpp

; 40   : 	lpf_cutoffFreq = cutoffFreq;

	movss	DWORD PTR [rcx+8], xmm0

; 41   : 
; 42   : 	// update lpf gains
; 43   : 	updateGains();

	call	?updateGains@LPFButterworth@@QEAAXXZ	; LPFButterworth::updateGains
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp

; 285  :         break;

	jmp	SHORT $LN18@setParamet
$LN12@setParamet:
; File E:\FoxSuite\fox-suite-blocks\include\utils.h

; 23   :     return minvalue + value * (maxValue - minvalue);

	mulss	xmm2, DWORD PTR __real@3f59999a
; File E:\FoxSuite\fox-suite-projects\Shimmer\Shimmer.cpp

; 278  :         BranchDelay->setFeedback(dev_BrDelFeedback);

	mov	rax, QWORD PTR [rcx+352]
	movss	DWORD PTR [rcx+276], xmm2
	movss	DWORD PTR [rax+56], xmm2
$LN18@setParamet:

; 306  :     }
; 307  :     default:
; 308  :         break;
; 309  :     }
; 310  : }

	mov	rbx, QWORD PTR [rsp+64]
	mov	rsi, QWORD PTR [rsp+72]
	movaps	xmm6, XMMWORD PTR [rsp+32]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
?setParameter@Shimmer@@UEAAXHM@Z ENDP			; Shimmer::setParameter
_TEXT	ENDS
END
