; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_R4Tremolo@@6B@				; Tremolo::`RTTI Complete Object Locator'
PUBLIC	??_R1A@?0A@EA@Tremolo@@8			; Tremolo::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3Tremolo@@8					; Tremolo::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_7Tremolo@@6B@				; Tremolo::`vftable'
PUBLIC	??_R0?AVTremolo@@@8				; Tremolo `RTTI Type Descriptor'
PUBLIC	??_R2Tremolo@@8					; Tremolo::`RTTI Base Class Array'
;	COMDAT ??_R2Tremolo@@8
rdata$r	SEGMENT
??_R2Tremolo@@8 DD imagerel ??_R1A@?0A@EA@Tremolo@@8	; Tremolo::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R0?AVTremolo@@@8
data$rs	SEGMENT
??_R0?AVTremolo@@@8 DQ FLAT:??_7type_info@@6B@		; Tremolo `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVTremolo@@', 00H
data$rs	ENDS
;	COMDAT ??_7Tremolo@@6B@
CONST	SEGMENT
??_7Tremolo@@6B@ DQ FLAT:??_R4Tremolo@@6B@		; Tremolo::`vftable'
	DQ	FLAT:?processAudio@Tremolo@@UEAAMM@Z
	DQ	FLAT:?setSampleRate@Tremolo@@UEAAXH@Z
CONST	ENDS
;	COMDAT ??_R3Tremolo@@8
rdata$r	SEGMENT
??_R3Tremolo@@8 DD 00H					; Tremolo::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2Tremolo@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@Tremolo@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@Tremolo@@8 DD imagerel ??_R0?AVTremolo@@@8 ; Tremolo::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3Tremolo@@8
rdata$r	ENDS
;	COMDAT ??_R4Tremolo@@6B@
rdata$r	SEGMENT
??_R4Tremolo@@6B@ DD 01H				; Tremolo::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVTremolo@@@8
	DD	imagerel ??_R3Tremolo@@8
	DD	imagerel ??_R4Tremolo@@6B@
PUBLIC	?setSampleRate@Tremolo@@UEAAXH@Z		; Tremolo::setSampleRate
PUBLIC	?processAudio@Tremolo@@UEAAMM@Z			; Tremolo::processAudio
PUBLIC	??1Tremolo@@QEAA@XZ				; Tremolo::~Tremolo
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processAudio@Tremolo@@UEAAMM@Z DD imagerel $LN4@processAud
	DD	imagerel $LN4@processAud+85
	DD	imagerel $unwind$?processAudio@Tremolo@@UEAAMM@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processAudio@Tremolo@@UEAAMM@Z DQ 00002680e00040e01r ; 3.3466e-309
	DD	030025206H
END
