; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_R1A@?0A@EA@LPFButterworth@@8			; LPFButterworth::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R2LPFButterworth@@8				; LPFButterworth::`RTTI Base Class Array'
PUBLIC	??_R0?AVLPFButterworth@@@8			; LPFButterworth `RTTI Type Descriptor'
PUBLIC	??_R4LPFButterworth@@6B@			; LPFButterworth::`RTTI Complete Object Locator'
PUBLIC	??_7LPFButterworth@@6B@				; LPFButterworth::`vftable'
PUBLIC	??_R3LPFButterworth@@8				; LPFButterworth::`RTTI Class Hierarchy Descriptor'
;	COMDAT ??_R3LPFButterworth@@8
rdata$r	SEGMENT
??_R3LPFButterworth@@8 DD 00H				; LPFButterworth::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2LPFButterworth@@8
rdata$r	ENDS
;	COMDAT ??_7LPFButterworth@@6B@
CONST	SEGMENT
??_7LPFButterworth@@6B@ DQ FLAT:??_R4LPFButterworth@@6B@ ; LPFButterworth::`vftable'
	DQ	FLAT:?processAudio@LPFButterworth@@UEAAMM@Z
CONST	ENDS
;	COMDAT ??_R4LPFButterworth@@6B@
rdata$r	SEGMENT
??_R4LPFButterworth@@6B@ DD 01H				; LPFButterworth::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVLPFButterworth@@@8
	DD	imagerel ??_R3LPFButterworth@@8
	DD	imagerel ??_R4LPFButterworth@@6B@
rdata$r	ENDS
;	COMDAT ??_R0?AVLPFButterworth@@@8
data$rs	SEGMENT
??_R0?AVLPFButterworth@@@8 DQ FLAT:??_7type_info@@6B@	; LPFButterworth `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVLPFButterworth@@', 00H
data$rs	ENDS
;	COMDAT ??_R2LPFButterworth@@8
rdata$r	SEGMENT
??_R2LPFButterworth@@8 DD imagerel ??_R1A@?0A@EA@LPFButterworth@@8 ; LPFButterworth::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@LPFButterworth@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@LPFButterworth@@8 DD imagerel ??_R0?AVLPFButterworth@@@8 ; LPFButterworth::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3LPFButterworth@@8
PUBLIC	?processAudio@LPFButterworth@@UEAAMM@Z		; LPFButterworth::processAudio
PUBLIC	?updateBuffers@LPFButterworth@@QEAAXMM@Z	; LPFButterworth::updateBuffers
PUBLIC	?updateGains@LPFButterworth@@QEAAXXZ		; LPFButterworth::updateGains
PUBLIC	?setSampleRate@LPFButterworth@@QEAAXH@Z		; LPFButterworth::setSampleRate
PUBLIC	?setCutoffFrequency@LPFButterworth@@QEAAXM@Z	; LPFButterworth::setCutoffFrequency
PUBLIC	?init@LPFButterworth@@QEAAXH@Z			; LPFButterworth::init
PUBLIC	??1LPFButterworth@@QEAA@XZ			; LPFButterworth::~LPFButterworth
PUBLIC	??0LPFButterworth@@QEAA@XZ			; LPFButterworth::LPFButterworth
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processAudio@LPFButterworth@@UEAAMM@Z DD imagerel $LN6@processAud
	DD	imagerel $LN6@processAud+113
	DD	imagerel $unwind$?processAudio@LPFButterworth@@UEAAMM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?updateGains@LPFButterworth@@QEAAXXZ DD imagerel $LN4@updateGain
	DD	imagerel $LN4@updateGain+264
	DD	imagerel $unwind$?updateGains@LPFButterworth@@QEAAXXZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$?updateGains@LPFButterworth@@QEAAXXZ DQ 00002a83d000a3d01r ; 3.69526e-309
	DQ	00004882f00039834r		; 6.30248e-309
	DQ	03004b2080005782ar		; 2.23412e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processAudio@LPFButterworth@@UEAAMM@Z DQ 00000682e00032e01r ; 5.65936e-310
	DD	02204H
END
