; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	DllMain
PUBLIC	MAIN
PUBLIC	VSTPluginMain
;	COMDAT pdata
pdata	SEGMENT
$pdata$VSTPluginMain DD imagerel $LN12@VSTPluginM
	DD	imagerel $LN12@VSTPluginM+95
	DD	imagerel $unwind$VSTPluginMain
;	COMDAT xdata
xdata	SEGMENT
$unwind$VSTPluginMain DQ 03002520600020601r	; 1.97773e-77
END
