; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

	TITLE	E:\FoxSuite\misefx\MisEfx\Debug\CombFilter.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	??0CombFilter@@QAE@XZ				; CombFilter::CombFilter
PUBLIC	??1CombFilter@@QAE@XZ				; CombFilter::~CombFilter
PUBLIC	?setFeedback@CombFilter@@QAEXM@Z		; CombFilter::setFeedback
PUBLIC	?setFeedbackFromDecay@CombFilter@@QAEXM@Z	; CombFilter::setFeedbackFromDecay
PUBLIC	?processAudio@CombFilter@@UAEMM@Z		; CombFilter::processAudio
PUBLIC	?setFeedbackToNegative@CombFilter@@QAEXXZ	; CombFilter::setFeedbackToNegative
PUBLIC	?setFeedbackToPositive@CombFilter@@QAEXXZ	; CombFilter::setFeedbackToPositive
PUBLIC	??_7CombFilter@@6B@				; CombFilter::`vftable'
PUBLIC	??_R4CombFilter@@6B@				; CombFilter::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCombFilter@@@8				; CombFilter `RTTI Type Descriptor'
PUBLIC	??_R3CombFilter@@8				; CombFilter::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CombFilter@@8				; CombFilter::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CombFilter@@8			; CombFilter::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@Delay@@8				; Delay::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVDelay@@@8				; Delay `RTTI Type Descriptor'
PUBLIC	??_R3Delay@@8					; Delay::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2Delay@@8					; Delay::`RTTI Base Class Array'
PUBLIC	__real@4024000000000000
PUBLIC	__real@447a0000
PUBLIC	__real@c0400000
EXTRN	??0Delay@@QAE@XZ:PROC				; Delay::Delay
EXTRN	??1Delay@@QAE@XZ:PROC				; Delay::~Delay
EXTRN	?init@Delay@@UAEXMH@Z:PROC			; Delay::init
EXTRN	?setSampleRate@Delay@@UAEXH@Z:PROC		; Delay::setSampleRate
EXTRN	?updateIndices@Delay@@QAEXXZ:PROC		; Delay::updateIndices
EXTRN	?writeToDelayLine@Delay@@QAEXM@Z:PROC		; Delay::writeToDelayLine
EXTRN	?readFromDelayLine@Delay@@QAEMXZ:PROC		; Delay::readFromDelayLine
EXTRN	_pow:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	__fltused:DWORD
;	COMDAT __real@c0400000
CONST	SEGMENT
__real@c0400000 DD 0c0400000r			; -3
CONST	ENDS
;	COMDAT __real@447a0000
CONST	SEGMENT
__real@447a0000 DD 0447a0000r			; 1000
CONST	ENDS
;	COMDAT __real@4024000000000000
CONST	SEGMENT
__real@4024000000000000 DQ 04024000000000000r	; 10
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_R2Delay@@8
rdata$r	SEGMENT
??_R2Delay@@8 DD FLAT:??_R1A@?0A@EA@Delay@@8		; Delay::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3Delay@@8
rdata$r	SEGMENT
??_R3Delay@@8 DD 00H					; Delay::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2Delay@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVDelay@@@8
data$rs	SEGMENT
??_R0?AVDelay@@@8 DD FLAT:??_7type_info@@6B@		; Delay `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVDelay@@', 00H
data$rs	ENDS
;	COMDAT ??_R1A@?0A@EA@Delay@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@Delay@@8 DD FLAT:??_R0?AVDelay@@@8	; Delay::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3Delay@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CombFilter@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CombFilter@@8 DD FLAT:??_R0?AVCombFilter@@@8 ; CombFilter::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CombFilter@@8
rdata$r	ENDS
;	COMDAT ??_R2CombFilter@@8
rdata$r	SEGMENT
??_R2CombFilter@@8 DD FLAT:??_R1A@?0A@EA@CombFilter@@8	; CombFilter::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@Delay@@8
rdata$r	ENDS
;	COMDAT ??_R3CombFilter@@8
rdata$r	SEGMENT
??_R3CombFilter@@8 DD 00H				; CombFilter::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2CombFilter@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCombFilter@@@8
data$rs	SEGMENT
??_R0?AVCombFilter@@@8 DD FLAT:??_7type_info@@6B@	; CombFilter `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCombFilter@@', 00H
data$rs	ENDS
;	COMDAT ??_R4CombFilter@@6B@
rdata$r	SEGMENT
??_R4CombFilter@@6B@ DD 00H				; CombFilter::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCombFilter@@@8
	DD	FLAT:??_R3CombFilter@@8
rdata$r	ENDS
;	COMDAT ??_7CombFilter@@6B@
CONST	SEGMENT
??_7CombFilter@@6B@ DD FLAT:??_R4CombFilter@@6B@	; CombFilter::`vftable'
	DD	FLAT:?init@Delay@@UAEXMH@Z
	DD	FLAT:?setSampleRate@Delay@@UAEXH@Z
	DD	FLAT:?processAudio@CombFilter@@UAEMM@Z
CONST	ENDS
; Function compile flags: /Odtp /RTCsu
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
?setFeedbackToPositive@CombFilter@@QAEXXZ PROC		; CombFilter::setFeedbackToPositive
; _this$ = ecx

; 58   : {	

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 59   : 	cf_feedbackGainSign = 1;

	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+52], 1

; 60   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?setFeedbackToPositive@CombFilter@@QAEXXZ ENDP		; CombFilter::setFeedbackToPositive
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
?setFeedbackToNegative@CombFilter@@QAEXXZ PROC		; CombFilter::setFeedbackToNegative
; _this$ = ecx

; 53   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 54   : 	cf_feedbackGainSign = -1;

	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+52], -1

; 55   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?setFeedbackToNegative@CombFilter@@QAEXXZ ENDP		; CombFilter::setFeedbackToNegative
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
_TEXT	SEGMENT
tv132 = -16						; size = 4
_buff$ = -12						; size = 4
_yn$ = -8						; size = 4
_this$ = -4						; size = 4
_xn$ = 8						; size = 4
?processAudio@CombFilter@@UAEMM@Z PROC			; CombFilter::processAudio
; _this$ = ecx

; 35   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
	mov	eax, -858993460				; ccccccccH
	mov	DWORD PTR [ebp-16], eax
	mov	DWORD PTR [ebp-12], eax
	mov	DWORD PTR [ebp-8], eax
	mov	DWORD PTR [ebp-4], eax
	mov	DWORD PTR _this$[ebp], ecx

; 36   : 	// Extract value from delay buffer
; 37   : 	float yn = readFromDelayLine();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?readFromDelayLine@Delay@@QAEMXZ	; Delay::readFromDelayLine
	fstp	DWORD PTR _yn$[ebp]

; 38   : 	
; 39   : 	// compute value to be stored in delay buffer
; 40   : 	float buff = xn + cf_feedbackGain * yn;

	mov	eax, DWORD PTR _this$[ebp]
	movss	xmm0, DWORD PTR [eax+44]
	mulss	xmm0, DWORD PTR _yn$[ebp]
	addss	xmm0, DWORD PTR _xn$[ebp]
	movss	DWORD PTR _buff$[ebp], xmm0

; 41   : 
; 42   : 	// write the value to delay buffer
; 43   : 	writeToDelayLine(buff);

	push	ecx
	movss	xmm0, DWORD PTR _buff$[ebp]
	movss	DWORD PTR [esp], xmm0
	mov	ecx, DWORD PTR _this$[ebp]
	call	?writeToDelayLine@Delay@@QAEXM@Z	; Delay::writeToDelayLine

; 44   : 
; 45   : 	// aggiorna gli indici
; 46   : 	updateIndices();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?updateIndices@Delay@@QAEXXZ		; Delay::updateIndices

; 47   : 
; 48   : 	// return output value
; 49   : 	return yn * dly_makeUpGain;

	mov	ecx, DWORD PTR _this$[ebp]
	movss	xmm0, DWORD PTR _yn$[ebp]
	mulss	xmm0, DWORD PTR [ecx+40]
	movss	DWORD PTR tv132[ebp], xmm0
	fld	DWORD PTR tv132[ebp]

; 50   : }

	add	esp, 16					; 00000010H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?processAudio@CombFilter@@UAEMM@Z ENDP			; CombFilter::processAudio
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
_TEXT	SEGMENT
_feedbackModule$ = -8					; size = 4
_this$ = -4						; size = 4
_decayInSeconds$ = 8					; size = 4
?setFeedbackFromDecay@CombFilter@@QAEXM@Z PROC		; CombFilter::setFeedbackFromDecay
; _this$ = ecx

; 23   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR [ebp-8], -858993460		; ccccccccH
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx

; 24   : 	// set decay
; 25   : 	cf_decayInSeconds = decayInSeconds;

	mov	eax, DWORD PTR _this$[ebp]
	movss	xmm0, DWORD PTR _decayInSeconds$[ebp]
	movss	DWORD PTR [eax+48], xmm0

; 26   : 	
; 27   : 	// compute comb filter gain module according to given decay value (in seconds)
; 28   : 	float feedbackModule = pow(10, -3 * dly_delayInmsec / (cf_decayInSeconds * 1000));

	mov	ecx, DWORD PTR _this$[ebp]
	movss	xmm0, DWORD PTR __real@c0400000
	mulss	xmm0, DWORD PTR [ecx+20]
	mov	edx, DWORD PTR _this$[ebp]
	movss	xmm1, DWORD PTR [edx+48]
	mulss	xmm1, DWORD PTR __real@447a0000
	divss	xmm0, xmm1
	cvtss2sd xmm0, xmm0
	sub	esp, 8
	movsd	QWORD PTR [esp], xmm0
	sub	esp, 8
	movsd	xmm0, QWORD PTR __real@4024000000000000
	movsd	QWORD PTR [esp], xmm0
	call	_pow
	add	esp, 16					; 00000010H
	fstp	DWORD PTR _feedbackModule$[ebp]

; 29   : 
; 30   : 	// allocate comb filter gain value retaining its sign
; 31   : 	cf_feedbackGain = cf_feedbackGainSign * feedbackModule;

	mov	eax, DWORD PTR _this$[ebp]
	cvtsi2ss xmm0, DWORD PTR [eax+52]
	mulss	xmm0, DWORD PTR _feedbackModule$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	movss	DWORD PTR [ecx+44], xmm0

; 32   : }

	add	esp, 8
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?setFeedbackFromDecay@CombFilter@@QAEXM@Z ENDP		; CombFilter::setFeedbackFromDecay
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
_g$ = 8							; size = 4
?setFeedback@CombFilter@@QAEXM@Z PROC			; CombFilter::setFeedback
; _this$ = ecx

; 18   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 19   : 	cf_feedbackGain = g;

	mov	eax, DWORD PTR _this$[ebp]
	movss	xmm0, DWORD PTR _g$[ebp]
	movss	DWORD PTR [eax+44], xmm0

; 20   : }

	mov	esp, ebp
	pop	ebp
	ret	4
?setFeedback@CombFilter@@QAEXM@Z ENDP			; CombFilter::setFeedback
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1CombFilter@@QAE@XZ PROC				; CombFilter::~CombFilter
; _this$ = ecx

; 15   : CombFilter::~CombFilter() {}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CombFilter@@6B@
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1Delay@@QAE@XZ			; Delay::~Delay
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CombFilter@@QAE@XZ ENDP				; CombFilter::~CombFilter
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File E:\FoxSuite\fox-suite-blocks\src\CombFilter.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0CombFilter@@QAE@XZ PROC				; CombFilter::CombFilter
; _this$ = ecx

; 8    : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx

; 7    : CombFilter::CombFilter() : Delay()

	mov	ecx, DWORD PTR _this$[ebp]
	call	??0Delay@@QAE@XZ			; Delay::Delay

; 8    : {

	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CombFilter@@6B@

; 9    : 	cf_feedbackGain     = 0.0;

	mov	ecx, DWORD PTR _this$[ebp]
	xorps	xmm0, xmm0
	movss	DWORD PTR [ecx+44], xmm0

; 10   : 	cf_decayInSeconds   = 0.0;

	mov	edx, DWORD PTR _this$[ebp]
	xorps	xmm0, xmm0
	movss	DWORD PTR [edx+48], xmm0

; 11   : 	cf_feedbackGainSign = 1;

	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+52], 1

; 12   : }

	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??0CombFilter@@QAE@XZ ENDP				; CombFilter::CombFilter
_TEXT	ENDS
END
